const { describe, test, expect } = require('bun:test');
const path = require('path');
const fs = require('fs');
const os = require('os');

const { scaffoldBeadsSync } = require('../lib/beads-sync-scaffold');

const GENERATED_MARKER = '# Generated by Forge GitHub-Beads sync\n';
const PACKAGE_ROOT = path.join(__dirname, '..');

function createTmpProject() {
  const projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'beads-sync-scaffold-'));
  return {
    projectRoot,
    cleanup: () => fs.rmSync(projectRoot, { recursive: true, force: true })
  };
}

function writeGeneratedLegacyFile(root, file) {
  const fullPath = path.join(root, file);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });

  const packageSource = path.join(__dirname, '..', file);
  if (fs.existsSync(packageSource)) {
    fs.copyFileSync(packageSource, fullPath);
    return;
  }

  fs.writeFileSync(fullPath, `${GENERATED_MARKER}${file}\n`, 'utf8');
}

describe('scaffoldBeadsSync', () => {
  test('is a deprecated no-op for new installs', () => {
    const { projectRoot, cleanup } = createTmpProject();
    try {
      const result = scaffoldBeadsSync(projectRoot, PACKAGE_ROOT);

      expect(result).toMatchObject({
        filesCreated: [],
        filesSkipped: [],
        filesRemoved: [],
        deprecated: true,
      });
      expect(result.message).toContain('Forge Kernel/server authority');
      expect(fs.existsSync(path.join(projectRoot, '.github', 'workflows', 'github-to-beads.yml'))).toBe(false);
    } finally {
      cleanup();
    }
  });

  test('removes deprecated generated sync files from existing installs', () => {
    const { projectRoot, cleanup } = createTmpProject();
    try {
      const oldFiles = [
        '.github/workflows/github-to-beads.yml',
        '.github/workflows/beads-to-github.yml',
        '.github/beads-mapping.json',
        'scripts/github-beads-sync.config.json',
        'scripts/github-beads-sync/index.mjs',
        'scripts/github-beads-sync/reverse-sync-cli.mjs',
      ];
      for (const file of oldFiles) {
        writeGeneratedLegacyFile(projectRoot, file);
      }

      const result = scaffoldBeadsSync(projectRoot, PACKAGE_ROOT);

      for (const file of oldFiles) {
        expect(fs.existsSync(path.join(projectRoot, file))).toBe(false);
        expect(result.filesRemoved).toContain(file);
      }
    } finally {
      cleanup();
    }
  });

  test('preserves unrelated workflow files', () => {
    const { projectRoot, cleanup } = createTmpProject();
    try {
      const unrelated = path.join(projectRoot, '.github', 'workflows', 'test.yml');
      fs.mkdirSync(path.dirname(unrelated), { recursive: true });
      fs.writeFileSync(unrelated, 'name: test\n');

      scaffoldBeadsSync(projectRoot, __dirname);

      expect(fs.readFileSync(unrelated, 'utf8')).toBe('name: test\n');
    } finally {
      cleanup();
    }
  });

  test('preserves customized legacy sync files', () => {
    const { projectRoot, cleanup } = createTmpProject();
    try {
      const customFiles = [
        '.github/workflows/github-to-beads.yml',
        'scripts/github-beads-sync/index.mjs',
      ];
      for (const file of customFiles) {
        const fullPath = path.join(projectRoot, file);
        fs.mkdirSync(path.dirname(fullPath), { recursive: true });
        fs.writeFileSync(fullPath, `custom team-owned ${file}\n`, 'utf8');
      }

      const result = scaffoldBeadsSync(projectRoot, path.join(__dirname, '..'));

      for (const file of customFiles) {
        expect(fs.readFileSync(path.join(projectRoot, file), 'utf8')).toBe(`custom team-owned ${file}\n`);
        expect(result.filesRemoved).not.toContain(file);
      }
    } finally {
      cleanup();
    }
  });

  test('removes legacy .github sync scaffold files when they are generated', () => {
    const { projectRoot, cleanup } = createTmpProject();
    try {
      const oldFiles = [
        '.github/beads-sync-config.json',
        '.github/scripts/beads-sync/index.mjs',
        '.github/scripts/beads-sync/reverse-sync-cli.mjs',
      ];
      for (const file of oldFiles) {
        writeGeneratedLegacyFile(projectRoot, file);
      }

      const result = scaffoldBeadsSync(projectRoot, path.join(__dirname, '..'));

      for (const file of oldFiles) {
        expect(fs.existsSync(path.join(projectRoot, file))).toBe(false);
        expect(result.filesRemoved).toContain(file);
      }
      expect(fs.existsSync(path.join(projectRoot, '.github', 'scripts', 'beads-sync'))).toBe(false);
    } finally {
      cleanup();
    }
  });
});
