const { describe, test, expect, beforeEach, afterEach } = require('bun:test');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { cleanupDeprecatedSyncFiles } = require('../lib/deprecated-sync-cleanup');

describe('cleanupDeprecatedSyncFiles', () => {
  let projectRoot;

  beforeEach(() => {
    projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'deprecated-sync-cleanup-'));
  });

  afterEach(() => {
    fs.rmSync(projectRoot, { recursive: true, force: true });
  });

  test('removes generated legacy sync files', () => {
    const file = path.join(projectRoot, '.github', 'scripts', 'beads-sync', 'index.mjs');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, '# Generated by Forge GitHub-Beads sync\nconsole.log("old");\n');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).toContain('.github/scripts/beads-sync/index.mjs');
    expect(fs.existsSync(file)).toBe(false);
    expect(fs.existsSync(path.dirname(file))).toBe(false);
  });

  test('preserves matching paths without generated identity', () => {
    const file = path.join(projectRoot, '.github', 'workflows', 'github-to-beads.yml');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, 'name: team-owned sync workflow\n');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).not.toContain('.github/workflows/github-to-beads.yml');
    expect(fs.readFileSync(file, 'utf8')).toBe('name: team-owned sync workflow\n');
  });

  test('treats packaged legacy templates as generated files', () => {
    const packageDir = fs.mkdtempSync(path.join(os.tmpdir(), 'deprecated-sync-package-'));
    const packageFile = path.join(packageDir, 'scripts', 'github-beads-sync', 'index.mjs');
    const projectFile = path.join(projectRoot, '.github', 'scripts', 'beads-sync', 'index.mjs');
    try {
      fs.mkdirSync(path.dirname(packageFile), { recursive: true });
      fs.mkdirSync(path.dirname(projectFile), { recursive: true });
      fs.writeFileSync(packageFile, 'console.log("packaged legacy sync");\n');
      fs.writeFileSync(projectFile, 'console.log("packaged legacy sync");\n');

      const result = cleanupDeprecatedSyncFiles(projectRoot, { packageDir });

      expect(result.removed).toContain('.github/scripts/beads-sync/index.mjs');
      expect(fs.existsSync(projectFile)).toBe(false);
    } finally {
      fs.rmSync(packageDir, { recursive: true, force: true });
    }
  });

  test('removes exact legacy script copies without package sources', () => {
    const legacyContent = fs.readFileSync(
      path.join(__dirname, '..', 'scripts', 'github-beads-sync', 'index.mjs'),
      'utf8',
    );
    const oldFiles = [
      'scripts/github-beads-sync/index.mjs',
      '.github/scripts/beads-sync/index.mjs',
    ];
    for (const file of oldFiles) {
      const fullPath = path.join(projectRoot, file);
      fs.mkdirSync(path.dirname(fullPath), { recursive: true });
      fs.writeFileSync(fullPath, legacyContent, 'utf8');
    }

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    for (const file of oldFiles) {
      expect(result.removed).toContain(file);
      expect(fs.existsSync(path.join(projectRoot, file))).toBe(false);
    }
  });

  test('removes the generated mapping stub without a trailing newline', () => {
    const file = path.join(projectRoot, '.github', 'beads-mapping.json');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, '{}', 'utf8');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).toContain('.github/beads-mapping.json');
    expect(fs.existsSync(file)).toBe(false);
  });

  test('removes generated reverse-sync workflow after default branch templating', () => {
    const file = path.join(projectRoot, '.github', 'workflows', 'beads-to-github.yml');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, [
      'name: Beads → GitHub Issue Sync',
      '',
      'on:',
      '  push:',
      '    branches: [main]',
      '    paths:',
      "      - '.beads/**'",
      '',
      '# Serialize with forward-sync to prevent race conditions',
      'concurrency:',
      '  group: beads-sync',
      '  cancel-in-progress: false',
      '',
      'permissions:',
      '  contents: read',
      '  issues: write',
      '',
      'jobs:',
      '  reverse-sync:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - name: Guard — skip loop commits',
      '        env:',
      '          COMMIT_MSG: ${{ github.event.head_commit.message }}',
      '        run: |',
      '          if [[ "$COMMIT_MSG" == chore\\(beads\\):* ]]; then',
      '            echo "Loop guard: skipping chore(beads): commit"',
      '            echo "SKIP=true" >> "$GITHUB_ENV"',
      '          fi',
      '',
      '      - name: Checkout current',
      "        if: env.SKIP != 'true'",
      '        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4',
      '        with:',
      '          fetch-depth: 0',
      '',
      '      - name: Detect and close',
      "        if: env.SKIP != 'true'",
      '        env:',
      '          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
      '          BEFORE_SHA: ${{ github.event.before }}',
      '        run: |',
      '          # Get old and new versions of .beads/issues.jsonl',
      '          # Use github.event.before (pre-push SHA) to catch multi-commit pushes',
      '          if [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ] || [ -z "$BEFORE_SHA" ]; then',
      '            OLD_CONTENT=""',
      '          else',
      '            OLD_CONTENT=$(git show "$BEFORE_SHA":.beads/issues.jsonl 2>/dev/null || echo "")',
      '          fi',
      '          NEW_CONTENT=$(cat .beads/issues.jsonl 2>/dev/null || echo "")',
      '',
      '          # Export via temp files to avoid shell injection',
      "          printf '%s' \"$OLD_CONTENT\" > /tmp/old-issues.jsonl",
      "          printf '%s' \"$NEW_CONTENT\" > /tmp/new-issues.jsonl",
      '',
      '          node scripts/github-beads-sync/reverse-sync-cli.mjs /tmp/old-issues.jsonl /tmp/new-issues.jsonl',
      ''
    ].join('\n'), 'utf8');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).toContain('.github/workflows/beads-to-github.yml');
    expect(fs.existsSync(file)).toBe(false);
  });
});
