const { describe, test, expect, beforeEach, afterEach } = require('bun:test');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { cleanupDeprecatedSyncFiles } = require('../lib/deprecated-sync-cleanup');

describe('cleanupDeprecatedSyncFiles', () => {
  let projectRoot;

  beforeEach(() => {
    projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'deprecated-sync-cleanup-'));
  });

  afterEach(() => {
    fs.rmSync(projectRoot, { recursive: true, force: true });
  });

  test('removes generated legacy sync files', () => {
    const file = path.join(projectRoot, '.github', 'scripts', 'beads-sync', 'index.mjs');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, '# Generated by Forge GitHub-Beads sync\nconsole.log("old");\n');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).toContain('.github/scripts/beads-sync/index.mjs');
    expect(fs.existsSync(file)).toBe(false);
    expect(fs.existsSync(path.dirname(file))).toBe(false);
  });

  test('preserves matching paths without generated identity', () => {
    const file = path.join(projectRoot, '.github', 'workflows', 'github-to-beads.yml');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, 'name: team-owned sync workflow\n');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).not.toContain('.github/workflows/github-to-beads.yml');
    expect(fs.readFileSync(file, 'utf8')).toBe('name: team-owned sync workflow\n');
  });

  test('treats packaged legacy templates as generated files', () => {
    const packageDir = fs.mkdtempSync(path.join(os.tmpdir(), 'deprecated-sync-package-'));
    const packageFile = path.join(packageDir, 'scripts', 'github-beads-sync', 'index.mjs');
    const projectFile = path.join(projectRoot, '.github', 'scripts', 'beads-sync', 'index.mjs');
    try {
      fs.mkdirSync(path.dirname(packageFile), { recursive: true });
      fs.mkdirSync(path.dirname(projectFile), { recursive: true });
      fs.writeFileSync(packageFile, 'console.log("packaged legacy sync");\n');
      fs.writeFileSync(projectFile, 'console.log("packaged legacy sync");\n');

      const result = cleanupDeprecatedSyncFiles(projectRoot, { packageDir });

      expect(result.removed).toContain('.github/scripts/beads-sync/index.mjs');
      expect(fs.existsSync(projectFile)).toBe(false);
    } finally {
      fs.rmSync(packageDir, { recursive: true, force: true });
    }
  });
});
