const { describe, test, expect, beforeEach, afterEach } = require('bun:test');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { cleanupDeprecatedSyncFiles } = require('../lib/deprecated-sync-cleanup');

describe('cleanupDeprecatedSyncFiles', () => {
  let projectRoot;

  beforeEach(() => {
    projectRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'deprecated-sync-cleanup-'));
  });

  afterEach(() => {
    fs.rmSync(projectRoot, { recursive: true, force: true });
  });

  test('removes generated legacy sync files', () => {
    const file = path.join(projectRoot, '.github', 'scripts', 'beads-sync', 'index.mjs');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, '# Generated by Forge GitHub-Beads sync\nconsole.log("old");\n');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).toContain('.github/scripts/beads-sync/index.mjs');
    expect(fs.existsSync(file)).toBe(false);
    expect(fs.existsSync(path.dirname(file))).toBe(false);
  });

  test('preserves matching paths without generated identity', () => {
    const file = path.join(projectRoot, '.github', 'workflows', 'github-to-beads.yml');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, 'name: team-owned sync workflow\n');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).not.toContain('.github/workflows/github-to-beads.yml');
    expect(fs.readFileSync(file, 'utf8')).toBe('name: team-owned sync workflow\n');
  });

  test('removes older generated forward sync workflow by historical hash', () => {
    const file = path.join(projectRoot, '.github', 'workflows', 'github-to-beads.yml');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, [
      'name: GitHub Issue \u2192 Beads Sync',
      '',
      'on:',
      '  issues:',
      '    types: [opened, closed]',
      '',
      '# CRITICAL: Serialize all beads writes to prevent mapping file corruption',
      'concurrency:',
      '  group: beads-sync',
      '  cancel-in-progress: false',
      '',
      'permissions:',
      '  contents: write   # push .beads/ and mapping file',
      '  issues: write     # post/edit bot comments',
      '',
      'jobs:',
      '  sync:',
      '    runs-on: ubuntu-latest',
      '    # Skip if triggered by the bot itself (loop prevention)',
      "    if: github.actor != 'github-actions[bot]'",
      '    steps:',
      '      - name: Checkout code',
      '        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4',
      '        with:',
      '          # Need full history for push',
      '          fetch-depth: 0',
      '          # Use default GITHUB_TOKEN',
      '          token: ${{ secrets.GITHUB_TOKEN }}',
      '',
      '      - name: Setup Bun',
      '        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2',
      '',
      '      - name: Install Beads CLI',
      '        run: bun add -g @beads/bd@^0.49',
      '',
      '      - name: Run sync',
      '        env:',
      '          GITHUB_EVENT_PATH: ${{ github.event_path }}',
      '          GITHUB_REPOSITORY: ${{ github.repository }}',
      '          SYNC_ACTION: ${{ github.event.action }}',
      '          BEADS_SYNC_CONFIG: scripts/github-beads-sync.config.json',
      '        run: |',
      '          node scripts/github-beads-sync/index.mjs "$SYNC_ACTION"',
      '',
      '      - name: Commit and push changes',
      '        env:',
      '          ISSUE_NUM: ${{ github.event.issue.number }}',
      '        run: |',
      '          git config user.name "github-actions[bot]"',
      '          git config user.email "github-actions[bot]@users.noreply.github.com"',
      '',
      '          # Stage beads and mapping changes',
      '          git add .beads/ .github/beads-mapping.json || true',
      '',
      '          # Only commit if there are changes',
      '          if git diff --cached --quiet; then',
      '            echo "No changes to commit"',
      '          else',
      '            git commit -m "chore(beads): sync from GitHub issue #${ISSUE_NUM}"',
      '',
      '            # Push with retry (handles concurrent runs)',
      '            push_success=false',
      '            for i in 1 2 3; do',
      '              if git push; then',
      '                echo "Push succeeded on attempt $i"',
      '                push_success=true',
      '                break',
      '              fi',
      '              echo "Push failed, attempt $i/3 \u2014 pulling with rebase..."',
      '              git rebase --abort 2>/dev/null || true',
      '              git pull --rebase',
      '            done',
      '            if [ "$push_success" = false ]; then',
      '              echo "::error::All 3 push attempts failed"',
      '              exit 1',
      '            fi',
      '          fi',
      ''
    ].join('\n'), 'utf8');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).toContain('.github/workflows/github-to-beads.yml');
    expect(fs.existsSync(file)).toBe(false);
  });

  test('removes older generated helper modules by historical hash', () => {
    const file = path.join(projectRoot, 'scripts', 'github-beads-sync', 'run-bd.mjs');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, [
      '/**',
      ' * @module run-bd',
      ' * @description Wrapper around the `bd` (Beads) CLI for GitHub-Beads sync.',
      ' *',
      ' * Exports pure arg-building and output-parsing functions (unit-testable),',
      ' * plus thin exec wrappers that shell out to the real `bd` binary.',
      ' */',
      '',
      "import { execFileSync } from 'node:child_process';",
      '',
      "const EXEC_OPTS = { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] };",
      '',
      '// ---------------------------------------------------------------------------',
      '// Arg builders (pure)',
      '// ---------------------------------------------------------------------------',
      '',
      '/**',
      ' * Build args array for `bd create`.',
      ' * Omits flags whose values are null or undefined.',
      ' * @param {object} opts',
      ' * @param {string} opts.title',
      ' * @param {string} [opts.type]',
      ' * @param {number|string} [opts.priority]',
      ' * @param {string} [opts.assignee]',
      ' * @param {string} [opts.description]',
      ' * @param {string} [opts.externalRef]',
      ' * @returns {string[]}',
      ' */',
      'export function buildCreateArgs({ title, type, priority, assignee, description, externalRef } = {}) {',
      "  const args = ['create', '--title', title];",
      '',
      "  if (type != null) args.push('--type', type);",
      "  if (priority != null) args.push('--priority', String(priority));",
      "  if (assignee != null) args.push('--assignee', assignee);",
      "  if (description != null) args.push('--description', description);",
      "  if (externalRef != null) args.push('--external-ref', externalRef);",
      '',
      '  return args;',
      '}',
      '',
      '/**',
      ' * Build args array for `bd close`.',
      ' * @param {string} beadsId',
      ' * @param {string} [reason]',
      ' * @returns {string[]}',
      ' */',
      'export function buildCloseArgs(beadsId, reason) {',
      "  const args = ['close', beadsId];",
      "  if (reason != null) args.push('--reason', reason);",
      '  return args;',
      '}',
      '',
      '/**',
      ' * Build args array for `bd show`.',
      ' * @param {string} beadsId',
      ' * @returns {string[]}',
      ' */',
      'export function buildShowArgs(beadsId) {',
      "  return ['show', beadsId, '--json'];",
      '}',
      '',
      '/**',
      ' * Build args array for `bd search`.',
      ' * @param {string} query',
      ' * @returns {string[]}',
      ' */',
      'export function buildSearchArgs(query) {',
      "  return ['search', query];",
      '}',
      '',
      '// ---------------------------------------------------------------------------',
      '// Output parsers (pure)',
      '// ---------------------------------------------------------------------------',
      '',
      '/**',
      ' * Extract beads ID from `bd create` stdout.',
      ' * Expects pattern: "Created issue: forge-xxxx"',
      ' * @param {string} stdout',
      ' * @returns {string|null}',
      ' */',
      'export function parseCreateOutput(stdout) {',
      '  const match = stdout.match(/Created issue:\\s+(forge-[\\w-]+)/);',
      '  if (match) return match[1];',
      '  // Fallback: loose match for any forge-prefixed ID anywhere in output',
      '  const fallback = stdout.match(/(forge-[a-z0-9]+)/i);',
      '  return fallback ? fallback[1] : null;',
      '}',
      '',
      '/**',
      ' * Extract status from `bd show --json` stdout.',
      ' * Parses JSON output for reliable status extraction.',
      ' * @param {string} stdout - JSON output from `bd show --json`',
      ' * @returns {string|null} Lowercase status or null',
      ' */',
      'export function parseShowOutput(stdout) {',
      '  try {',
      '    const data = JSON.parse(stdout);',
      '    const issue = Array.isArray(data) ? data[0] : data;',
      '    return issue?.status ? issue.status.toLowerCase() : null;',
      '  } catch (_err) {',
      '    return null;',
      '  }',
      '}',
      '',
      '// ---------------------------------------------------------------------------',
      '// Exec wrappers (side-effectful \u2014 not unit-tested)',
      '// ---------------------------------------------------------------------------',
      '',
      '/**',
      ' * Run `bd create` and return the parsed beads ID.',
      ' * @param {object} opts - Same as buildCreateArgs',
      ' * @returns {string|null} The created beads ID, or null if parsing failed',
      ' */',
      'export function bdCreate(opts) {',
      '  try {',
      "    const stdout = execFileSync('bd', buildCreateArgs(opts), EXEC_OPTS);",
      '    const id = parseCreateOutput(stdout);',
      '    if (!id) {',
      "      console.error('bd create succeeded but ID not parsed. stdout:', stdout);",
      '    }',
      '    return id;',
      '  } catch (err) {',
      "    console.error('bd create failed:', err.stderr?.toString() || err.message);",
      '    return null;',
      '  }',
      '}',
      '',
      '/**',
      ' * Run `bd close`.',
      ' * @param {string} beadsId',
      ' * @param {string} [reason]',
      ' */',
      'export function bdClose(beadsId, reason) {',
      "  execFileSync('bd', buildCloseArgs(beadsId, reason), EXEC_OPTS);",
      '}',
      '',
      '/**',
      ' * Run `bd show` and return the parsed status.',
      ' * Returns null if bd exits non-zero (e.g., deleted issue, corrupted .beads/).',
      ' * @param {string} beadsId',
      ' * @returns {string|null} Lowercase status or null',
      ' */',
      'export function bdShow(beadsId) {',
      '  try {',
      "    const stdout = execFileSync('bd', buildShowArgs(beadsId), EXEC_OPTS);",
      '    return parseShowOutput(stdout);',
      '  } catch (_err) {',
      '    return null;',
      '  }',
      '}',
      '',
      '/**',
      ' * Run `bd search` and return raw stdout.',
      ' * @param {string} query',
      ' * @returns {string}',
      ' */',
      'export function bdSearch(query) {',
      "  return execFileSync('bd', buildSearchArgs(query), EXEC_OPTS);",
      '}',
      ''
    ].join('\n'), 'utf8');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).toContain('scripts/github-beads-sync/run-bd.mjs');
    expect(fs.existsSync(file)).toBe(false);
  });

  test('preserves generated helper modules when a customized sync workflow remains', () => {
    const customWorkflow = path.join(projectRoot, '.github', 'workflows', 'github-to-beads.yml');
    const generatedHelper = path.join(projectRoot, 'scripts', 'github-beads-sync', 'index.mjs');
    const legacyContent = fs.readFileSync(
      path.join(__dirname, '..', 'scripts', 'github-beads-sync', 'index.mjs'),
      'utf8',
    );
    fs.mkdirSync(path.dirname(customWorkflow), { recursive: true });
    fs.mkdirSync(path.dirname(generatedHelper), { recursive: true });
    fs.writeFileSync(customWorkflow, 'name: team-owned sync workflow\n', 'utf8');
    fs.writeFileSync(generatedHelper, legacyContent, 'utf8');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).not.toContain('.github/workflows/github-to-beads.yml');
    expect(result.removed).not.toContain('scripts/github-beads-sync/index.mjs');
    expect(fs.readFileSync(customWorkflow, 'utf8')).toBe('name: team-owned sync workflow\n');
    expect(fs.readFileSync(generatedHelper, 'utf8')).toBe(legacyContent);
  });

  test('treats packaged legacy templates as generated files', () => {
    const packageDir = fs.mkdtempSync(path.join(os.tmpdir(), 'deprecated-sync-package-'));
    const packageFile = path.join(packageDir, 'scripts', 'github-beads-sync', 'index.mjs');
    const projectFile = path.join(projectRoot, '.github', 'scripts', 'beads-sync', 'index.mjs');
    try {
      fs.mkdirSync(path.dirname(packageFile), { recursive: true });
      fs.mkdirSync(path.dirname(projectFile), { recursive: true });
      fs.writeFileSync(packageFile, 'console.log("packaged legacy sync");\n');
      fs.writeFileSync(projectFile, 'console.log("packaged legacy sync");\n');

      const result = cleanupDeprecatedSyncFiles(projectRoot, { packageDir });

      expect(result.removed).toContain('.github/scripts/beads-sync/index.mjs');
      expect(fs.existsSync(projectFile)).toBe(false);
    } finally {
      fs.rmSync(packageDir, { recursive: true, force: true });
    }
  });

  test('removes exact legacy script copies without package sources', () => {
    const legacyContent = fs.readFileSync(
      path.join(__dirname, '..', 'scripts', 'github-beads-sync', 'index.mjs'),
      'utf8',
    );
    const oldFiles = [
      'scripts/github-beads-sync/index.mjs',
      '.github/scripts/beads-sync/index.mjs',
    ];
    for (const file of oldFiles) {
      const fullPath = path.join(projectRoot, file);
      fs.mkdirSync(path.dirname(fullPath), { recursive: true });
      fs.writeFileSync(fullPath, legacyContent, 'utf8');
    }

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    for (const file of oldFiles) {
      expect(result.removed).toContain(file);
      expect(fs.existsSync(path.join(projectRoot, file))).toBe(false);
    }
  });

  test('removes the generated mapping stub without a trailing newline', () => {
    const file = path.join(projectRoot, '.github', 'beads-mapping.json');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, '{}', 'utf8');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).toContain('.github/beads-mapping.json');
    expect(fs.existsSync(file)).toBe(false);
  });

  test('removes generated reverse-sync workflow after default branch templating', () => {
    const file = path.join(projectRoot, '.github', 'workflows', 'beads-to-github.yml');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, [
      'name: Beads → GitHub Issue Sync',
      '',
      'on:',
      '  push:',
      '    branches: [main]',
      '    paths:',
      "      - '.beads/**'",
      '',
      '# Serialize with forward-sync to prevent race conditions',
      'concurrency:',
      '  group: beads-sync',
      '  cancel-in-progress: false',
      '',
      'permissions:',
      '  contents: read',
      '  issues: write',
      '',
      'jobs:',
      '  reverse-sync:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - name: Guard — skip loop commits',
      '        env:',
      '          COMMIT_MSG: ${{ github.event.head_commit.message }}',
      '        run: |',
      '          if [[ "$COMMIT_MSG" == chore\\(beads\\):* ]]; then',
      '            echo "Loop guard: skipping chore(beads): commit"',
      '            echo "SKIP=true" >> "$GITHUB_ENV"',
      '          fi',
      '',
      '      - name: Checkout current',
      "        if: env.SKIP != 'true'",
      '        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4',
      '        with:',
      '          fetch-depth: 0',
      '',
      '      - name: Detect and close',
      "        if: env.SKIP != 'true'",
      '        env:',
      '          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
      '          BEFORE_SHA: ${{ github.event.before }}',
      '        run: |',
      '          # Get old and new versions of .beads/issues.jsonl',
      '          # Use github.event.before (pre-push SHA) to catch multi-commit pushes',
      '          if [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ] || [ -z "$BEFORE_SHA" ]; then',
      '            OLD_CONTENT=""',
      '          else',
      '            OLD_CONTENT=$(git show "$BEFORE_SHA":.beads/issues.jsonl 2>/dev/null || echo "")',
      '          fi',
      '          NEW_CONTENT=$(cat .beads/issues.jsonl 2>/dev/null || echo "")',
      '',
      '          # Export via temp files to avoid shell injection',
      "          printf '%s' \"$OLD_CONTENT\" > /tmp/old-issues.jsonl",
      "          printf '%s' \"$NEW_CONTENT\" > /tmp/new-issues.jsonl",
      '',
      '          node scripts/github-beads-sync/reverse-sync-cli.mjs /tmp/old-issues.jsonl /tmp/new-issues.jsonl',
      ''
    ].join('\n'), 'utf8');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).toContain('.github/workflows/beads-to-github.yml');
    expect(fs.existsSync(file)).toBe(false);
  });

  test('preserves generated-looking reverse-sync workflow with customized branch list', () => {
    const file = path.join(projectRoot, '.github', 'workflows', 'beads-to-github.yml');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, [
      'name: Beads â†’ GitHub Issue Sync',
      '',
      'on:',
      '  push:',
      '    branches: [main, release]',
      '    paths:',
      "      - '.beads/**'",
      '',
      '# Serialize with forward-sync to prevent race conditions',
      'concurrency:',
      '  group: beads-sync',
      '  cancel-in-progress: false',
      '',
      'permissions:',
      '  contents: read',
      '  issues: write',
      '',
      'jobs:',
      '  reverse-sync:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - name: Guard â€” skip loop commits',
      '        env:',
      '          COMMIT_MSG: ${{ github.event.head_commit.message }}',
      '        run: |',
      '          if [[ "$COMMIT_MSG" == chore\\(beads\\):* ]]; then',
      '            echo "Loop guard: skipping chore(beads): commit"',
      '            echo "SKIP=true" >> "$GITHUB_ENV"',
      '          fi',
      '',
      '      - name: Checkout current',
      "        if: env.SKIP != 'true'",
      '        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4',
      '        with:',
      '          fetch-depth: 0',
      '',
      '      - name: Detect and close',
      "        if: env.SKIP != 'true'",
      '        env:',
      '          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
      '          BEFORE_SHA: ${{ github.event.before }}',
      '        run: |',
      '          # Get old and new versions of .beads/issues.jsonl',
      '          # Use github.event.before (pre-push SHA) to catch multi-commit pushes',
      '          if [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ] || [ -z "$BEFORE_SHA" ]; then',
      '            OLD_CONTENT=""',
      '          else',
      '            OLD_CONTENT=$(git show "$BEFORE_SHA":.beads/issues.jsonl 2>/dev/null || echo "")',
      '          fi',
      '          NEW_CONTENT=$(cat .beads/issues.jsonl 2>/dev/null || echo "")',
      '',
      '          # Export via temp files to avoid shell injection',
      "          printf '%s' \"$OLD_CONTENT\" > /tmp/old-issues.jsonl",
      "          printf '%s' \"$NEW_CONTENT\" > /tmp/new-issues.jsonl",
      '',
      '          node scripts/github-beads-sync/reverse-sync-cli.mjs /tmp/old-issues.jsonl /tmp/new-issues.jsonl',
      ''
    ].join('\n'), 'utf8');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).not.toContain('.github/workflows/beads-to-github.yml');
    expect(fs.existsSync(file)).toBe(true);
  });

  test('preserves exact legacy reverse-sync workflow when branch list was customized', () => {
    const file = path.join(projectRoot, '.github', 'workflows', 'beads-to-github.yml');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, [
      'name: Beads \u2192 GitHub Issue Sync',
      '',
      'on:',
      '  push:',
      '    branches: [main, release]',
      '    paths:',
      "      - '.beads/**'",
      '',
      '# Serialize with forward-sync to prevent race conditions',
      'concurrency:',
      '  group: beads-sync',
      '  cancel-in-progress: false',
      '',
      'permissions:',
      '  contents: read',
      '  issues: write',
      '',
      'jobs:',
      '  reverse-sync:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - name: Guard \u2014 skip loop commits',
      '        env:',
      '          COMMIT_MSG: ${{ github.event.head_commit.message }}',
      '        run: |',
      '          if [[ "$COMMIT_MSG" == chore\\(beads\\):* ]]; then',
      '            echo "Loop guard: skipping chore(beads): commit"',
      '            echo "SKIP=true" >> "$GITHUB_ENV"',
      '          fi',
      '',
      '      - name: Checkout current',
      "        if: env.SKIP != 'true'",
      '        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4',
      '        with:',
      '          fetch-depth: 0',
      '',
      '      - name: Detect and close',
      "        if: env.SKIP != 'true'",
      '        env:',
      '          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}',
      '          BEFORE_SHA: ${{ github.event.before }}',
      '        run: |',
      '          # Get old and new versions of .beads/issues.jsonl',
      '          # Use github.event.before (pre-push SHA) to catch multi-commit pushes',
      '          if [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ] || [ -z "$BEFORE_SHA" ]; then',
      '            OLD_CONTENT=""',
      '          else',
      '            OLD_CONTENT=$(git show "$BEFORE_SHA":.beads/issues.jsonl 2>/dev/null || echo "")',
      '          fi',
      '          NEW_CONTENT=$(cat .beads/issues.jsonl 2>/dev/null || echo "")',
      '',
      '          # Export via temp files to avoid shell injection',
      "          printf '%s' \"$OLD_CONTENT\" > /tmp/old-issues.jsonl",
      "          printf '%s' \"$NEW_CONTENT\" > /tmp/new-issues.jsonl",
      '',
      '          node scripts/github-beads-sync/reverse-sync-cli.mjs /tmp/old-issues.jsonl /tmp/new-issues.jsonl',
      ''
    ].join('\n'), 'utf8');

    const result = cleanupDeprecatedSyncFiles(projectRoot);

    expect(result.removed).not.toContain('.github/workflows/beads-to-github.yml');
    expect(fs.existsSync(file)).toBe(true);
  });
});
