const { describe, expect, test } = require('bun:test');
const { execFileSync } = require('node:child_process');
const path = require('node:path');

const {
  CAPABILITY_IDS,
  HARNESS_IDS,
  STAGE_IDS,
  UTILITY_SKILL_IDS,
  buildHarnessCapabilityEvidence,
  getHarnessCapabilityMatrix,
  getRendererContract,
  getSkillsFirstStageGraph,
} = require('../lib/harness-capability-matrix');

const ROOT = path.resolve(__dirname, '..');

describe('harness capability matrix', () => {
  test('covers every v3.0 harness and parity capability', () => {
    const matrix = getHarnessCapabilityMatrix();

    expect(Object.keys(matrix.harnesses)).toEqual(HARNESS_IDS);
    for (const harnessId of HARNESS_IDS) {
      expect(Object.keys(matrix.harnesses[harnessId].capabilities)).toEqual(CAPABILITY_IDS);
    }
  });

  test('models Cursor skills and rules as different surfaces', () => {
    const cursor = getHarnessCapabilityMatrix().harnesses.cursor.capabilities;

    // Cursor skills ARE generated by Forge at setup (.cursor/skills), so 'native' — not 'unproven'.
    expect(cursor.skills.status).toBe('native');
    expect(cursor.skills.primarySurface).toBe('.cursor/skills/<skill>/SKILL.md');
    expect(cursor.skills.role).toBe('on-demand workflow');
    expect(cursor.skills.evidence).toContain('S10');
    expect(cursor.rules.primarySurface).toBe('.cursor/rules/<rule>.mdc');
    expect(cursor.rules.role).toBe('always-on or scoped policy');
    expect(cursor.rules.activation).toContain('description');
  });

  test('records unsupported/not-yet-delivered harness surfaces honestly', () => {
    const matrix = getHarnessCapabilityMatrix();

    // Hooks: Claude + Cursor native hook configs ARE now rendered by setup
    // (lib/hook-renderer.js), projecting Forge's TDD-gate + protected-path
    // enforcement onto native surfaces. Codex stays honest (global-config scope).
    expect(matrix.harnesses.claude.capabilities.hooks.status).toBe('native');
    expect(matrix.harnesses.claude.capabilities.hooks.primarySurface).toBe('.claude/settings.json');
    expect(matrix.harnesses.cursor.capabilities.hooks.status).toBe('native');
    expect(matrix.harnesses.cursor.capabilities.hooks.primarySurface).toBe('.cursor/hooks.json');
    expect(matrix.harnesses.codex.capabilities.hooks.status).toBe('not-delivered');
    expect(matrix.harnesses.codex.capabilities.hooks.knownIssue).toContain('global');
    // Agents domain is unimplemented for every harness.
    expect(matrix.harnesses.claude.capabilities.agents.status).toBe('not-delivered');
    expect(matrix.harnesses.cursor.capabilities.agents.status).toBe('not-delivered');
    // typedMemory is write-only, no projection renderer.
    expect(matrix.harnesses.claude.capabilities.typedMemory.status).toBe('not-delivered');
    // Codex MCP is global-config-only; not wired at project setup.
    expect(matrix.harnesses.codex.capabilities.mcp.status).toBe('not-delivered');
    expect(matrix.harnesses.claude.capabilities.commands.status).toBe('removed');
    expect(matrix.harnesses.claude.capabilities.commands.role).toContain('legacy .claude/commands/ surface removed');
    expect(matrix.harnesses.cursor.capabilities.commands.status).toBe('removed');
    expect(matrix.harnesses.cursor.capabilities.mcp.primarySurface).toBe('.cursor/mcp.json');
    expect(matrix.harnesses.cursor.capabilities.extensionPacks.primarySurface).toContain('.cursor/mcp.json');
  });

  test('models native safety surfaces honestly (Tier-2 parity)', () => {
    const matrix = getHarnessCapabilityMatrix();
    const { claude, cursor, codex, hermes } = matrix.harnesses;

    // Claude tool-permission allowlist is a real project-local render (.claude/settings.json).
    expect(claude.capabilities.permissions.status).toBe('native');
    expect(claude.capabilities.permissions.primarySurface).toContain('.claude/settings.json');
    expect(claude.capabilities.permissions.evidence).toContain('S11');
    // Cursor has no project-local permission allowlist (IDE/global only).
    expect(cursor.capabilities.permissions.status).toBe('unsupported');
    // Codex approvals/sandbox are config.toml surfaces honored only under GLOBAL trust — deferred.
    expect(codex.capabilities.permissions.status).toBe('not-delivered');
    expect(codex.capabilities.sandbox.status).toBe('not-delivered');
    expect(codex.capabilities.sandbox.knownIssue).toContain('trust');
    expect(codex.capabilities.sandbox.evidence).toContain('S13');

    // Cursor .cursorignore IS a native project-local read/index boundary.
    expect(cursor.capabilities.ignore.status).toBe('native');
    expect(cursor.capabilities.ignore.primarySurface).toBe('.cursorignore');
    expect(cursor.capabilities.ignore.evidence).toContain('S12');
    // Claude read boundary is projected into permission deny rules (no .claudeignore).
    expect(claude.capabilities.ignore.status).toBe('projection');

    // Claude has no config-file sandbox; execution safety is the permissions allowlist.
    expect(claude.capabilities.sandbox.status).toBe('unsupported');
    // Hermes is CLI-consumed: no native safety surfaces.
    expect(hermes.capabilities.permissions.status).toBe('unsupported');
    expect(hermes.capabilities.sandbox.status).toBe('unsupported');
  });

  test('every capability status is in the STATUS_VOCABULARY enum (no off-vocab/dishonest labels)', () => {
    const { STATUS_VOCABULARY } = require('../lib/harness-capability-matrix');
    const vocab = new Set(STATUS_VOCABULARY);
    const matrix = getHarnessCapabilityMatrix();
    const offenders = [];
    for (const harnessId of Object.keys(matrix.harnesses)) {
      const caps = matrix.harnesses[harnessId].capabilities;
      for (const [capId, cap] of Object.entries(caps)) {
        if (!vocab.has(cap.status)) offenders.push(`${harnessId}.${capId}=${cap.status}`);
      }
    }
    expect(offenders).toEqual([]);
    // Deprecated dishonest statuses must not resurface.
    expect(vocab.has('unproven')).toBe(false);
    expect(vocab.has('skill-backed')).toBe(false);
  });

  test('evidence object is machine-readable and source-backed', () => {
    const evidence = buildHarnessCapabilityEvidence();

    expect(evidence.kind).toBe('forge.harnessCapabilityEvidence');
    expect(evidence.schemaVersion).toBe('1.0.0');
    expect(evidence.harnesses.map(harness => harness.id)).toEqual(HARNESS_IDS);
    expect(evidence.sources.every(source => source.label && source.url)).toBe(true);
    expect(JSON.parse(JSON.stringify(evidence))).toEqual(evidence);
  });
});

describe('skills-first stage graph', () => {
  test('represents every default stage as a super skill with subskills', () => {
    const graph = getSkillsFirstStageGraph();

    expect(graph.stages.map(stage => stage.id)).toEqual(STAGE_IDS);
    expect(graph.stages.map(stage => stage.id)).not.toContain('status');
    for (const stage of graph.stages) {
      expect(stage.canonicalSurface).toBe('skill');
      expect(stage.workflowStage).toBe(true);
      expect(stage.superSkill).toBe(`${stage.id}`);
      expect(stage.subskills.length).toBeGreaterThan(0);
      expect(stage.renderTargets.claude.skill).toBe(`.claude/skills/${stage.id}/SKILL.md`);
      expect(stage.renderTargets.claude.commandShim).toBeUndefined();
      // Cursor stage skills ARE populated by Forge at setup — 'native', no rule-policy fallback.
      expect(stage.renderTargets.cursor.skill).toBe(`.cursor/skills/${stage.id}/SKILL.md`);
      expect(stage.renderTargets.cursor.status).toBe('native');
      expect(stage.renderTargets.cursor.rulePolicy).toBeUndefined();
      // .codex/skills is the staging mirror; the install target is $CODEX_HOME/skills.
      expect(stage.renderTargets.codex.stagingMirror).toBe(`.codex/skills/${stage.id}/SKILL.md`);
      expect(stage.renderTargets.codex.directRepoDiscoveryTarget).toBe(`.agents/skills/${stage.id}/SKILL.md`);
      // Hermes DOES get per-stage skill files (populateAgentSkills), consumed via CLI.
      expect(stage.renderTargets.hermes.skill).toBe(`.hermes/skills/${stage.id}/SKILL.md`);
      expect(stage.renderTargets.hermes.status).toBe('forge-owned');
    }
  });

  test('models status as a utility skill outside workflow stages', () => {
    const graph = getSkillsFirstStageGraph();

    expect(graph.utilitySkills.map(skill => skill.id)).toEqual(UTILITY_SKILL_IDS);
    expect(graph.utilitySkills).toContainEqual(expect.objectContaining({
      id: 'status',
      canonicalSurface: 'skill',
      workflowStage: false,
      superSkill: 'status',
    }));
  });

  test('renders Claude stages skill-first with NO command shim (commands removed in A0d)', () => {
    const graph = getSkillsFirstStageGraph();

    for (const stage of graph.stages) {
      // The legacy `.claude/commands/` surface was removed; the stage SKILL is
      // the authority. Emitting a command shim contradicted the commands
      // capability row (which records Claude commands as `removed`).
      expect(stage.renderTargets.claude.skill).toBe(`.claude/skills/${stage.id}/SKILL.md`);
      expect(stage.renderTargets.claude.commandShim).toBeUndefined();
    }
  });

  test('models Hermes stages as Forge-owned per-stage skill files (setup populates .hermes/skills)', () => {
    const graph = getSkillsFirstStageGraph();

    for (const stage of graph.stages) {
      // Forge populates .hermes/skills/<stage>/SKILL.md at setup (populateAgentSkills);
      // Hermes consumes them via the CLI. The earlier "no per-stage file" claim
      // contradicted setup reality and is corrected here.
      expect(stage.renderTargets.hermes.skill).toBe(`.hermes/skills/${stage.id}/SKILL.md`);
      expect(stage.renderTargets.hermes.status).toBe('forge-owned');
      expect(stage.renderTargets.hermes.via).toBe('forge orient / forge recap');
    }
  });

  test('exposes plan phases as addressable subskills', () => {
    const plan = getSkillsFirstStageGraph().stages.find(stage => stage.id === 'plan');

    expect(plan.subskills.map(subskill => subskill.id)).toEqual([
      'plan.intent_capture',
      'plan.parallel_research',
      'plan.parallel_critics',
      'plan.synthesis',
      'plan.final_lock',
    ]);
  });
});

describe('renderer contract', () => {
  test('requires renderer evidence before broad harness generation', () => {
    const contract = getRendererContract();

    expect(contract.scope).toBe('contract-only');
    expect(contract.beforeAddingRenderer).toEqual([
      'capability-matrix-entry',
      'target-path-contract',
      'activation-metadata-contract',
      'machine-readable-evidence',
      'known-issue-if-unproven',
    ]);
  });

  test('binds each renderer family to canonical Forge input and evidence', () => {
    const contract = getRendererContract();
    const rendererIds = contract.rendererFamilies.map(renderer => renderer.id);

    expect(rendererIds).toEqual([
      'instructions',
      'skills',
      'rules',
      'mcp',
      'hooks',
      'commands',
      'agents',
      'stage-graph',
      'state-and-memory',
      'distribution',
      'safety',
    ]);
    expect(contract.rendererFamilies.every(renderer => renderer.canonicalInput && renderer.requiredEvidence.length > 0)).toBe(true);
  });
});

describe('harness capability evidence CLI', () => {
  test('prints the matrix as JSON for machine-readable evidence', () => {
    const output = execFileSync(
      process.execPath,
      [path.join(ROOT, 'scripts', 'spikes', 'harness-capability-matrix.js')],
      { cwd: ROOT, encoding: 'utf8' },
    );
    const parsed = JSON.parse(output);

    expect(parsed.kind).toBe('forge.harnessCapabilityEvidence');
    expect(parsed.stageGraph.kind).toBe('forge.skillsFirstStageGraph');
    expect(parsed.rendererContract.kind).toBe('forge.harnessRendererContract');
  });
});
