const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { describe, test, expect, beforeEach, afterEach } = require('bun:test');
const { scaffoldGithubBeadsSync } = require('../lib/setup');

const GENERATED_MARKER = '# Generated by Forge GitHub-Beads sync\n';

async function writeGeneratedLegacyFile(root, file) {
  const fullPath = path.join(root, file);
  await fs.promises.mkdir(path.dirname(fullPath), { recursive: true });

  const packageSource = path.join(__dirname, '..', file);
  if (fs.existsSync(packageSource)) {
    await fs.promises.copyFile(packageSource, fullPath);
    return;
  }

  await fs.promises.writeFile(fullPath, `${GENERATED_MARKER}${file}\n`, 'utf8');
}

describe('deprecated GitHub-Beads sync setup cleanup', () => {
  let tmpDir;

  beforeEach(async () => {
    tmpDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'forge-sync-test-'));
  });

  afterEach(async () => {
    await fs.promises.rm(tmpDir, { recursive: true, force: true });
  });

  test('does not create sync files for new installs', async () => {
    const result = await scaffoldGithubBeadsSync(tmpDir, path.join(__dirname, '..'));

    expect(result).toMatchObject({
      created: [],
      skipped: [],
      deprecated: true,
    });
    expect(fs.existsSync(path.join(tmpDir, '.github', 'workflows', 'github-to-beads.yml'))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, '.github', 'workflows', 'beads-to-github.yml'))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, 'scripts', 'github-beads-sync'))).toBe(false);
  });

  test('removes old generated sync files from existing installs', async () => {
    const oldFiles = [
      '.github/workflows/github-to-beads.yml',
      '.github/workflows/beads-to-github.yml',
      '.github/beads-mapping.json',
      'scripts/github-beads-sync.config.json',
      'scripts/github-beads-sync/index.mjs',
      'scripts/github-beads-sync/reverse-sync-cli.mjs',
    ];
    for (const file of oldFiles) {
      await writeGeneratedLegacyFile(tmpDir, file);
    }

    const result = await scaffoldGithubBeadsSync(tmpDir, path.join(__dirname, '..'));

    for (const file of oldFiles) {
      expect(fs.existsSync(path.join(tmpDir, file))).toBe(false);
      expect(result.removed).toContain(file);
    }
  });

  test('preserves customized legacy sync files', async () => {
    const customFiles = [
      '.github/workflows/github-to-beads.yml',
      'scripts/github-beads-sync/index.mjs',
    ];
    for (const file of customFiles) {
      const fullPath = path.join(tmpDir, file);
      await fs.promises.mkdir(path.dirname(fullPath), { recursive: true });
      await fs.promises.writeFile(fullPath, `custom team-owned ${file}\n`, 'utf8');
    }

    const result = await scaffoldGithubBeadsSync(tmpDir, path.join(__dirname, '..'));

    for (const file of customFiles) {
      expect(fs.readFileSync(path.join(tmpDir, file), 'utf8')).toBe(`custom team-owned ${file}\n`);
      expect(result.removed).not.toContain(file);
    }
  });

  test('removes legacy .github sync scaffold files when they are generated', async () => {
    const oldFiles = [
      '.github/beads-sync-config.json',
      '.github/scripts/beads-sync/index.mjs',
      '.github/scripts/beads-sync/reverse-sync-cli.mjs',
    ];
    for (const file of oldFiles) {
      await writeGeneratedLegacyFile(tmpDir, file);
    }

    const result = await scaffoldGithubBeadsSync(tmpDir, path.join(__dirname, '..'));

    for (const file of oldFiles) {
      expect(fs.existsSync(path.join(tmpDir, file))).toBe(false);
      expect(result.removed).toContain(file);
    }
    expect(fs.existsSync(path.join(tmpDir, '.github', 'scripts', 'beads-sync'))).toBe(false);
  });

  test('does not remove unrelated workflow files', async () => {
    const unrelated = path.join(tmpDir, '.github', 'workflows', 'test.yml');
    await fs.promises.mkdir(path.dirname(unrelated), { recursive: true });
    await fs.promises.writeFile(unrelated, 'name: test\n', 'utf8');

    await scaffoldGithubBeadsSync(tmpDir, path.join(__dirname, '..'));

    expect(fs.readFileSync(unrelated, 'utf8')).toBe('name: test\n');
  });

  describe('forge.js integration', () => {
    const forgePath = path.join(__dirname, '..', 'bin', 'forge.js');
    const content = fs.readFileSync(forgePath, 'utf-8');

    test('--quick mode skips sync setup prompt', () => {
      const quickStart = content.indexOf('async function quickSetup');
      const quickEnd = content.indexOf('\nasync function ', quickStart + 1);
      const quickSection = content.substring(quickStart, quickEnd > quickStart ? quickEnd : quickStart + 3000);

      expect(quickSection).not.toContain('Beads issue sync');
      expect(quickSection).not.toContain('scaffoldGithubBeadsSync');
    });

    test('interactive setup no longer prompts for GitHub-Beads sync', () => {
      expect(content).not.toContain('Enable GitHub');
      expect(content).toContain('Beads GitHub sync scaffolding is deprecated (--sync).');
    });

    test('interactive external-service setup does not clean deprecated sync files', () => {
      const setupStart = content.indexOf('async function configureExternalServices');
      const setupEnd = content.indexOf('\nfunction showBanner', setupStart + 1);
      const setupSection = content.substring(setupStart, setupEnd > setupStart ? setupEnd : setupStart + 3000);

      expect(setupSection).not.toContain('scaffoldGithubBeadsSync');
    });

    test('bare deprecated --sync setup migrates local Beads state before cleanup', () => {
      const syncStart = content.indexOf('if (flags.sync && selectedAgents.length === 0)');
      const syncEnd = content.indexOf('return;', syncStart);
      const syncSection = content.substring(syncStart, syncEnd > syncStart ? syncEnd : syncStart + 500);

      expect(syncSection).toContain('migrateExistingBeadsLocalState();');
      expect(syncSection.indexOf('migrateExistingBeadsLocalState();'))
        .toBeLessThan(syncSection.indexOf('await handleSyncScaffold();'));
    });
  });

  describe('setup command integration', () => {
    const commandSetupPath = path.join(__dirname, '..', 'lib', 'commands', 'setup.js');
    const commandSetup = fs.readFileSync(commandSetupPath, 'utf-8');

    test('deprecated --sync setup does not require the GitHub CLI', () => {
      const helperStart = commandSetup.indexOf('function requiresGithubCliForSetup');
      const helperEnd = commandSetup.indexOf('\n}', helperStart);
      const helperSection = commandSetup.substring(helperStart, helperEnd > helperStart ? helperEnd : helperStart + 500);

      expect(helperSection).not.toContain('syncEnabled');
      expect(helperSection).not.toContain('options.syncEnabled');
    });

    test('bare deprecated --sync setup runs cleanup instead of interactive setup', () => {
      expect(commandSetup).toContain('if (flags.sync && selectedAgents.length === 0)');
      expect(commandSetup).toContain('await handleSyncScaffold();');
      expect(commandSetup.indexOf('if (flags.sync && selectedAgents.length === 0)'))
        .toBeLessThan(commandSetup.indexOf('await runInteractiveSetupFallback(flags);'));
    });

    test('external-service setup does not clean deprecated sync files', () => {
      const setupStart = commandSetup.indexOf('async function configureExternalServices');
      const setupEnd = commandSetup.indexOf('\nfunction showBanner', setupStart + 1);
      const setupSection = commandSetup.substring(setupStart, setupEnd > setupStart ? setupEnd : setupStart + 3000);

      expect(setupSection).not.toContain('scaffoldGithubBeadsSync');
    });
  });
});
