/**
 * Unit tests for the generated static command manifest.
 *
 * `lib/commands/_manifest.js` is generated by scripts/gen-command-manifest.js
 * and consumed by the registry as the bundleable fast path. These tests assert
 * the module's runtime contract (shape + every entry is a real command module).
 * The disk-vs-manifest drift guard lives in
 * test/structural/command-manifest-drift.test.js.
 */

const { describe, test, expect } = require('bun:test');
const path = require('node:path');

const manifest = require('../../lib/commands/_manifest');
const { validateCommand } = require('../../lib/commands/_registry');
const { METADATA_FIELDS } = require('../../scripts/gen-command-manifest');

describe('lib/commands/_manifest', () => {
  test('exports { dir, commands } with dir pointing at lib/commands', () => {
    expect(typeof manifest.dir).toBe('string');
    expect(path.basename(manifest.dir)).toBe('commands');
    expect(Array.isArray(manifest.commands)).toBe(true);
    expect(manifest.commands.length).toBeGreaterThan(0);
  });

  test('every entry has a filename and a loader for a valid command module', () => {
    for (const entry of manifest.commands) {
      expect(typeof entry.file).toBe('string');
      expect(entry.file.endsWith('.js')).toBe(true);
      expect(typeof entry.load).toBe('function');
      const validation = validateCommand(entry.load());
      expect(validation.valid).toBe(true);
    }
  });

  test('entry metadata matches the loaded module exports', () => {
    for (const entry of manifest.commands) {
      const mod = entry.load();
      for (const field of METADATA_FIELDS) {
        expect({ file: entry.file, field, value: entry[field] })
          .toEqual({ file: entry.file, field, value: mod[field] });
      }
    }
  });

  test('each loader requires its own command file', () => {
    for (const entry of manifest.commands) {
      expect(entry.load()).toBe(require(path.join(manifest.dir, entry.file)));
    }
  });

  test('entries are sorted by filename (deterministic)', () => {
    const files = manifest.commands.map(e => e.file);
    const sorted = [...files].sort();
    expect(files).toEqual(sorted);
  });

  test('command names are unique across entries', () => {
    const names = manifest.commands.map(e => e.name);
    expect(new Set(names).size).toBe(names.length);
  });
});
