'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { describe, test, expect, beforeAll, afterAll } = require('bun:test');
const yaml = require('js-yaml');

const ROOT = path.join(__dirname, '..', '..');
const WORKFLOW_PATH = path.join(ROOT, '.github', 'workflows', 'size-check.yml');
const PACK_TIMEOUT_MS = 120000;

function loadWorkflow() {
  return yaml.load(fs.readFileSync(WORKFLOW_PATH, 'utf8'));
}

function allSteps(workflow) {
  return Object.values(workflow.jobs).flatMap((job) => job.steps || []);
}

function runText(workflow) {
  return allSteps(workflow).map((s) => s.run || '').join('\n');
}

describe('.github/workflows/size-check.yml', () => {
  test('exists and is valid YAML with a size-related name', () => {
    expect(fs.existsSync(WORKFLOW_PATH)).toBe(true);
    const workflow = loadWorkflow();
    expect(workflow.name.toLowerCase()).toContain('size');
  });

  test('runs on push and pull_request to the default branches', () => {
    const workflow = loadWorkflow();
    expect(workflow.on.push.branches).toContain('master');
    expect(workflow.on.pull_request.branches).toContain('master');
  });

  test('runs on every PR and push, with no path filters a new publishable path could escape', () => {
    const workflow = loadWorkflow();
    for (const trigger of ['push', 'pull_request']) {
      expect(workflow.on[trigger].paths).toBeUndefined();
      expect(workflow.on[trigger]['paths-ignore']).toBeUndefined();
    }
  });

  test('is generated by forge release generate-size-workflow', () => {
    expect(fs.readFileSync(WORKFLOW_PATH, 'utf8')).toMatch(/^# Generated by `forge release generate-size-workflow`/);
  });

  test('checks out code on ubuntu-latest and installs dependencies (bundled deps need node_modules)', () => {
    const workflow = loadWorkflow();
    const job = workflow.jobs['size-check'];
    expect(job['runs-on']).toBe('ubuntu-latest');
    expect(allSteps(workflow).some((s) => (s.uses || '').startsWith('actions/checkout'))).toBe(true);
    expect(runText(workflow)).toContain('bun install');
  });

  test('measures the published package through the budget script, not the repo checkout', () => {
    const workflow = loadWorkflow();
    const text = runText(workflow);
    expect(text).toContain('node scripts/package-size-check.js');
    expect(text).not.toContain('du -sb');
  });

  test('reports to the step summary and needs no PR write permission', () => {
    const workflow = loadWorkflow();
    const job = workflow.jobs['size-check'];
    expect(job.permissions).toEqual({ contents: 'read' });
    expect(allSteps(workflow).some((s) => (s.uses || '').includes('github-script'))).toBe(false);
  });
});

describe('README badge integration', () => {
  test('README has the package size badge', () => {
    const content = fs.readFileSync(path.join(ROOT, 'README.md'), 'utf8');
    expect(content).toContain('size-check.yml/badge.svg');
  });
});

describe('committed baseline vs the real package', () => {
  const { runPack, check, MANIFEST_PATH, BASELINE_PATH } = require('../../scripts/package-size-check');
  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
  const baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf8'));

  // Regression for the old failure mode: the old check measured the whole repo
  // checkout, so repo-only files (docs/work/**, test/**) failed PRs that shipped
  // nothing. Plant large probes there before packing; they must not register.
  const probeDirs = [
    path.join(ROOT, 'docs', 'work', `.size-probe-${process.pid}`),
    path.join(ROOT, 'test', `.size-probe-${process.pid}`),
  ];
  let packText;

  beforeAll(() => {
    for (const dir of probeDirs) {
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'probe.bin'), Buffer.alloc(2 * 1024 * 1024));
    }
    packText = runPack(ROOT);
  }, PACK_TIMEOUT_MS);

  afterAll(() => {
    for (const dir of probeDirs) fs.rmSync(dir, { recursive: true, force: true });
  });

  test('the current package is within budget of the committed baseline', () => {
    const { result, report } = check({ packText, manifest, baseline });
    if (!result.ok) console.error(report);
    expect(result.failures).toEqual([]);
    expect(result.ok).toBe(true);
  });

  test('repo-only files growing in docs/work/** and test/** do not affect the result', () => {
    const { measured, result } = check({ packText, manifest, baseline });
    const probePaths = JSON.parse(packText)[0].files.map((f) => f.path).filter((p) => p.includes('.size-probe-'));
    expect(probePaths).toEqual([]);
    // 4MB of probes would have tripped the old whole-checkout measure on its own.
    expect(measured.total.unpacked).toBeLessThan(baseline.total.unpacked + 1024 * 1024);
    expect(result.ok).toBe(true);
  });

  test('the baseline records every manifest block plus other', () => {
    const expected = [...Object.keys(manifest.blocks), 'other'].sort();
    expect(Object.keys(baseline.blocks).sort()).toEqual(expected);
  });
});
