'use strict';

/**
 * Canonical rule source → Cursor native rule renderer.
 *
 * Forge policy rules (workflow, TDD, security, documentation) have ONE canonical
 * source in `rules/<name>.md`. Each canonical file is a THIN POINTER: a short
 * frontmatter (`description`, `globs`, `alwaysApply`) plus a few lines that point
 * at `AGENTS.md` and the relevant stage skill. The full policy bodies are NOT
 * duplicated here — they live in `AGENTS.md` and `skills/<stage>/SKILL.md`.
 *
 * Only ONE harness has a first-class native rule surface, so only one renderer
 * exists:
 *
 *   - Cursor : `.cursor/rules/<name>.mdc`  (MDC frontmatter + pointer body)
 *
 * Claude, Codex, and Hermes receive this same policy through their INSTRUCTION
 * projection (`CLAUDE.md` → `AGENTS.md`, `AGENTS.md`, `forge orient`) — adding
 * always-on `.claude/rules/*.md` files would triple-deliver the same policy into
 * every session as pure token bloat. See `lib/harness-capability-matrix.js`
 * (the `rules` row) and `docs/reference/AGENT_SKILL_PARITY.md`.
 *
 * The generated `.cursor/rules/*.mdc` files are NOT committed — they are produced
 * at `forge setup` from the canonical source (like the gitignored, setup-populated
 * skill dirs). The structural drift gate regenerates them into a temp dir and
 * asserts the render is deterministic and well-formed, rather than committing a
 * mirror. Never hand-edit a generated `.mdc` — edit `rules/<name>.md`.
 *
 * Dependency-free (no YAML/markdown deps) so it runs under `bun test` and the
 * release gates without pulling `@forge/*` workspaces.
 *
 * @module rules-sync
 */

const fs = require('node:fs');
const path = require('node:path');

/** Canonical rule source directory (relative to a repo/package root). */
const CANONICAL_RULES_DIR = 'rules';

/** Cursor native rule surface (relative to a project root). */
const CURSOR_RULES_DIR = '.cursor/rules';

/** Canonical rule name → Cursor `.mdc` filename. */
const CURSOR_RULE_FILES = {
  workflow: 'forge-workflow.mdc',
  tdd: 'tdd-enforcement.mdc',
  security: 'security-scanning.mdc',
  documentation: 'documentation.mdc',
};

const CANONICAL_RULE_NAMES = Object.keys(CURSOR_RULE_FILES);

const GENERATED_NOTE =
  'Generated by Forge from the canonical rules/ source. Do not edit — edit ' +
  'rules/<name>.md and re-run `forge setup` (or the rules renderer).';

/**
 * Parse the minimal YAML frontmatter Forge authors in canonical rule files.
 * Only flat `key: value` pairs are supported (values kept as raw strings so
 * arrays/booleans round-trip verbatim into the rendered output).
 *
 * @param {string} raw
 * @returns {{ meta: Record<string,string>, body: string }}
 */
function parseFrontmatter(raw) {
  const norm = String(raw).replace(/\r\n/g, '\n');
  if (!norm.startsWith('---\n')) {
    return { meta: {}, body: norm };
  }
  const end = norm.indexOf('\n---\n', 4);
  if (end === -1) {
    return { meta: {}, body: norm };
  }
  const block = norm.slice(4, end);
  const body = norm.slice(end + 5);
  const meta = {};
  for (const line of block.split('\n')) {
    const m = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
    if (m) meta[m[1]] = m[2].trim();
  }
  return { meta, body };
}

/** Body with leading blank lines removed and a single trailing newline. */
function normalizeBody(body) {
  return body.replace(/^\n+/, '').replace(/\s+$/, '') + '\n';
}

/**
 * Read one canonical rule from disk into a render-ready descriptor.
 *
 * @param {string} sourceRoot - Repo/package root containing `rules/`.
 * @param {string} name - Canonical rule name (stem of `rules/<name>.md`).
 * @returns {{ name, description, globs, alwaysApply, body }}
 */
function readCanonicalRule(sourceRoot, name) {
  const filePath = path.join(sourceRoot, CANONICAL_RULES_DIR, `${name}.md`);
  const raw = fs.readFileSync(filePath, 'utf-8');
  const { meta, body } = parseFrontmatter(raw);
  return {
    name,
    description: meta.description || '""',
    globs: meta.globs || '[]',
    alwaysApply: meta.alwaysApply || 'false',
    body: normalizeBody(body),
  };
}

/**
 * List all canonical rules (in stable CURSOR_RULE_FILES order).
 *
 * @param {string} sourceRoot - Repo/package root containing `rules/`.
 * @param {{ only?: Iterable<string> }} [options]
 * @returns {Array<ReturnType<typeof readCanonicalRule>>}
 */
function listCanonicalRules(sourceRoot, options = {}) {
  const only = options.only ? new Set(options.only) : null;
  return CANONICAL_RULE_NAMES
    .filter((name) => !only || only.has(name))
    .map((name) => readCanonicalRule(sourceRoot, name));
}

/** Render the Cursor native rule (`.mdc` — MDC frontmatter + pointer body). */
function renderCursorRule(rule) {
  const frontmatter = [
    '---',
    `description: ${rule.description}`,
    `globs: ${rule.globs}`,
    `alwaysApply: ${rule.alwaysApply}`,
    '---',
    '',
    `<!-- ${GENERATED_NOTE} -->`,
    '',
    '',
  ].join('\n');
  return frontmatter + rule.body;
}

/**
 * Render every canonical rule to Cursor `.mdc` content, keyed by output filename.
 * Pure with respect to the target filesystem (only reads canonical `rules/`),
 * so callers can diff two renders to prove determinism.
 *
 * @param {string} sourceRoot - Root containing canonical `rules/`.
 * @param {{ only?: Iterable<string> }} [options]
 * @returns {Record<string, string>} filename → rendered content
 */
function renderCursorRuleMap(sourceRoot, options = {}) {
  const map = {};
  for (const rule of listCanonicalRules(sourceRoot, options)) {
    map[CURSOR_RULE_FILES[rule.name]] = renderCursorRule(rule);
  }
  return map;
}

/**
 * Render canonical rules into a project's Cursor rule directory.
 *
 * @param {object} params
 * @param {string} params.sourceRoot - Root containing canonical `rules/`.
 * @param {string} params.targetRoot - Project root to write native rules under.
 * @param {'cursor'} [params.harness='cursor'] - Only Cursor has a native rule surface.
 * @param {boolean} [params.overwrite=false] - Overwrite existing files.
 * @param {Iterable<string>} [params.only] - Restrict to these canonical names.
 * @returns {{ written: string[], skipped: string[] }}
 */
function renderRulesForHarness({ sourceRoot, targetRoot, harness = 'cursor', overwrite = false, only }) {
  if (harness !== 'cursor') {
    throw new Error(
      `No native rule surface for harness "${harness}"; Claude/Codex/Hermes ` +
      'receive rule policy through their AGENTS.md instruction projection.',
    );
  }
  const outDir = path.join(targetRoot, CURSOR_RULES_DIR);
  fs.mkdirSync(outDir, { recursive: true });

  const map = renderCursorRuleMap(sourceRoot, { only });
  const written = [];
  const skipped = [];
  for (const [file, content] of Object.entries(map)) {
    const outPath = path.join(outDir, file);
    if (!overwrite && fs.existsSync(outPath)) {
      skipped.push(file);
      continue;
    }
    fs.writeFileSync(outPath, content, 'utf-8');
    written.push(file);
  }
  return { written, skipped };
}

/**
 * Structural drift gate for rules: regenerate into a temp dir and assert the
 * render is deterministic and well-formed. No committed mirror is compared —
 * the canonical `rules/` source is the only tracked artifact, and Cursor rules
 * are setup-populated (like the gitignored skill dirs).
 *
 * @param {object} params
 * @param {string} params.sourceRoot - Root containing canonical `rules/`.
 * @returns {{ ok: boolean, issues: object[], files: string[] }}
 */
function checkRulesRenderDeterminism({ sourceRoot }) {
  const issues = [];
  const first = renderCursorRuleMap(sourceRoot);
  const second = renderCursorRuleMap(sourceRoot);
  const files = Object.keys(first);

  for (const file of files) {
    if (first[file] !== second[file]) {
      issues.push({ file, status: 'non-deterministic' });
      continue;
    }
    const content = first[file];
    if (!content.startsWith('---\n')) {
      issues.push({ file, status: 'missing-frontmatter' });
    }
    if (!content.includes('description:')) {
      issues.push({ file, status: 'missing-description' });
    }
  }

  // Every canonical rule must map to exactly one Cursor output file.
  for (const name of CANONICAL_RULE_NAMES) {
    if (!files.includes(CURSOR_RULE_FILES[name])) {
      issues.push({ file: CURSOR_RULE_FILES[name], status: 'unrendered-canonical' });
    }
  }

  return { ok: issues.length === 0, issues, files };
}

module.exports = {
  CANONICAL_RULES_DIR,
  CURSOR_RULES_DIR,
  CURSOR_RULE_FILES,
  CANONICAL_RULE_NAMES,
  GENERATED_NOTE,
  parseFrontmatter,
  listCanonicalRules,
  readCanonicalRule,
  renderCursorRule,
  renderCursorRuleMap,
  renderRulesForHarness,
  checkRulesRenderDeterminism,
};
