/**
 * Static Command Manifest — GENERATED FILE, DO NOT EDIT.
 *
 * Regenerate with: node scripts/gen-command-manifest.js
 * Drift is enforced by test/structural/command-manifest-drift.test.js.
 *
 * Each entry carries the static metadata discovery and help need, snapshotted
 * from the command module's exports, plus a `load` closure with a static
 * relative `require` so `bun build --compile` can still bundle the command
 * graph. The registry (lib/commands/_registry.js) calls `load` only when a
 * command is dispatched, and falls back to `fs.readdirSync` auto-discovery for
 * dev/extension commands.
 *
 * @module commands/_manifest
 */

'use strict';

/**
 * @typedef {Object} ManifestEntry
 * @property {string} file - Command filename (e.g. `status.js`)
 * @property {string} name - Command name used for routing
 * @property {string} description - Human-readable description
 * @property {string} [usage] - Usage string
 * @property {Object<string, string>} [flags] - Flag descriptions
 * @property {boolean} [hidden] - Omitted from the global help listing
 * @property {function(): import("./_registry").CommandModule} load - Requires the command module
 */

/** @type {ManifestEntry[]} */
const commands = [
  {
    file: "adapter.js",
    name: "adapter",
    description: "Manage and test review adapters",
    usage: "forge adapter <test|list|enable|disable> ...",
    load: () => require("./adapter"),
  },
  {
    file: "add.js",
    name: "add",
    description: "Record an extension source in forge.lock",
    usage: "Usage: forge add <source> [--name <id>] [--allow-untrusted]",
    flags: {"--name":"Lockfile extension id to record","--allow-untrusted":"Explicitly record an untrusted remote/package source"},
    load: () => require("./add"),
  },
  {
    file: "audit.js",
    name: "audit",
    description: "Verify Forge lockfile and audit state",
    usage: "Usage: forge audit verify",
    load: () => require("./audit"),
  },
  {
    file: "blocked.js",
    name: "blocked",
    description: "Show blocked issues via Forge",
    usage: "forge issue blocked [flags]",
    flags: {},
    load: () => require("./blocked"),
  },
  {
    file: "claim.js",
    name: "claim",
    description: "Claim an issue via Forge",
    usage: "forge claim <id> [flags]",
    flags: {},
    load: () => require("./claim"),
  },
  {
    file: "claims.js",
    name: "claims",
    description: "Show active issue leases (claims) via Forge",
    usage: "forge issue claims [--json]",
    flags: {},
    load: () => require("./claims"),
  },
  {
    file: "clean.js",
    name: "clean",
    description: "Remove worktrees for merged branches (squash-aware) and fast-forward the default branch",
    usage: "forge clean [--dry-run] [--no-master-sync]",
    flags: {"--dry-run":"Show what would be cleaned without removing","--no-master-sync":"Do not fast-forward the main checkout default branch after cleaning"},
    load: () => require("./clean"),
  },
  {
    file: "close.js",
    name: "close",
    description: "Close an issue via Forge",
    usage: "forge close <id...> [flags]",
    flags: {},
    load: () => require("./close"),
  },
  {
    file: "comment.js",
    name: "comment",
    description: "Add an issue comment via Forge",
    usage: "forge comment <id> <body...>",
    flags: {},
    load: () => require("./comment"),
  },
  {
    file: "control.js",
    name: "control",
    description: "Set tri-state control (mandatory/optional/permission) for a gate or rail",
    usage: "Usage: forge control <gate-id|rail-id> <mandatory|optional|permission>\n       forge control status [--json]\n\nTri-state control for the gate/rail registry. These flags are DECLARED intent\n— today no runtime consumer denies on them (see the guarantee matrix). MCP/\nrules/skills are presence-only and refused — see docs/reference/control-plane-guarantees.md.",
    load: () => require("./control"),
  },
  {
    file: "create.js",
    name: "create",
    description: "Create an issue via Forge",
    usage: "forge create [title] [flags]",
    flags: {},
    load: () => require("./create"),
  },
  {
    file: "dev.js",
    name: "dev",
    description: "Run the TDD development stage with phase guidance",
    load: () => require("./dev"),
  },
  {
    file: "doc-gate.js",
    name: "doc-gate",
    description: "Detect a repository's structure, or enforce the doc-update gate on a PR",
    usage: "forge doc-gate detect [--json]\n       forge doc-gate check --base <ref> --head <ref> [--skip] [--json]\n       forge doc-gate init [--force] [--json]\n       forge doc-gate okf <status|enable|disable> [--json]\n       forge doc-gate okf generate [--source <dir>] [--out <dir>] [--json]\n       forge doc-gate okf link [--out <dir>] [--json]",
    flags: {"--json":"Emit a structured JSON object instead of the human summary.","--base":"check: base ref/SHA of the pull request.","--head":"check: head ref/SHA of the pull request.","--skip":"check: force a pass (e.g. a no-docs-needed label).","--force":"init: overwrite an existing .docgate.json.","--source":"okf generate: source docs dir (default: auto — docs/ or tracked markdown).","--out":"okf generate/link: bundle output dir (default: .okf)."},
    load: () => require("./doc-gate"),
  },
  {
    file: "doctor.js",
    name: "doctor",
    description: "Report the filesystem class of the kernel database path (cloud/network/local)",
    usage: "Usage: forge doctor [--json]",
    load: () => require("./doctor"),
  },
  {
    file: "explain.js",
    name: "explain",
    description: "Explain a runtime graph primitive",
    usage: "forge explain <id> [--json]",
    flags: {"--json":"Emit machine-readable JSON output"},
    load: () => require("./explain"),
  },
  {
    file: "export.js",
    name: "export",
    description: "Export the Kernel backlog to deterministic git-tracked JSONL (D16 portability projection)",
    usage: "forge export [--dir <path>] [--dry-run] [--json] [--import]",
    flags: {},
    load: () => require("./export"),
  },
  {
    file: "gate.js",
    name: "gate",
    description: "Toggle a workflow gate, or record/query human-gate approval events",
    usage: "Usage: forge gate <enable|disable|approve|reject|status|check> [<issue-id>] <gate-id> [--ttl <duration>] [--reason <text>] [--json]\n       forge gate doc <detect|check|init|okf|...> [args]   (doc-update gate; = forge doc-gate, run `forge doc-gate --help`)",
    load: () => require("./gate"),
  },
  {
    file: "github.js",
    name: "github",
    description: "Optional clone-local GitHub account selection, automatic routing, and isolated launch",
    usage: "forge github use <login> [--auto] | auto [--disable] | router --uninstall --force | status [--json] | unset | run -- <program> [args...]",
    load: () => require("./github"),
  },
  {
    file: "hooks.js",
    name: "hooks",
    description: "Opt-in install of Forge native hooks into GLOBAL harness config (Codex/Hermes)",
    usage: "Usage: forge hooks install --global [--harness codex|hermes|all] [--dry-run]\n       forge hooks session-start --harness <claude> (machine-facing; emits SessionStart context)\n       forge hooks inbox-pickup --harness <claude> (machine-facing; emits UserPromptSubmit context)\n       forge hooks shepherd-events --harness <claude> (machine-facing; emits UserPromptSubmit PR-monitor deltas)\n       forge hooks memory-recall --harness <claude> (machine-facing; emits UserPromptSubmit query-relevant memory)\n       forge hooks read-attention --harness <claude> (machine-facing; emits path-matched PreToolUse:Read context)\n       forge hooks capture --harness <claude> --trigger <precompact|stop> (machine-facing; captures a session summary on exit)",
    flags: {"--global":"Required consent flag — this command writes home-directory config","--harness":"codex | hermes | all (default: all)","--dry-run":"Preview the merge without writing anything"},
    load: () => require("./hooks"),
  },
  {
    file: "inbox.js",
    name: "inbox",
    description: "List and ack targeted dashboard instruction comments (compliant comment-back)",
    usage: "Usage: forge inbox [--json]\n       forge inbox ack <comment_id>",
    flags: {"--json":"Machine-readable envelope for the dashboard / scripts"},
    load: () => require("./inbox"),
  },
  {
    file: "init.js",
    name: "init",
    description: "Initialize Forge adoption config in a fresh repository",
    usage: "Usage: forge init [--profile minimal|standard|full] [--classification critical|standard|refactor] [--harness claude,cursor,codex] [--yes] [--force] [--dry-run]\n\nInitialize the day-one .forge skeleton for a fresh repository.",
    flags: {"--profile <name>":"Adoption profile: minimal, standard, or full","--minimal":"Shortcut for --profile minimal --yes","--standard":"Shortcut for --profile standard --yes","--full":"Shortcut for --profile full --yes","--classification <name>":"Default workflow classification: critical, standard, or refactor","--harness <targets>":"Comma-separated harness targets: claude, cursor, codex","--yes":"Use the standard profile when no profile is provided","--force":"Overwrite existing day-one .forge files","--dry-run":"Print the generated config YAML without writing files"},
    load: () => require("./init"),
  },
  {
    file: "insights.js",
    name: "insights",
    description: "Detect recurring evidence patterns and suggest conservative workflow follow-ups",
    usage: "Usage: forge insights [--limit N] [--min-count N] [--since YYYY-MM-DD] [--json]\n       forge insights accept <candidate-id> [--note text]\n       forge insights reject <candidate-id> [--note text]",
    load: () => require("./insights"),
  },
  {
    file: "issue.js",
    name: "issue",
    description: "Manage issues through the Forge command surface",
    usage: "forge issue <create|update|claim|release|close|show|list|ready|search|stats|dep> [...]",
    flags: {},
    load: () => require("./issue"),
  },
  {
    file: "issues.js",
    name: "issues",
    description: "Manage issues through the Forge authority layer",
    usage: "forge issues <subcommand> [...]",
    flags: {},
    hidden: true,
    load: () => require("./issues"),
  },
  {
    file: "lint.js",
    name: "lint",
    description: "Show issues missing required content via Forge",
    usage: "forge issue lint",
    flags: {},
    load: () => require("./lint"),
  },
  {
    file: "list.js",
    name: "list",
    description: "List issues via Forge",
    usage: "forge list [flags]",
    flags: {},
    load: () => require("./list"),
  },
  {
    file: "memory.js",
    name: "memory",
    description: "Unified memory surface: add, recall, search, insights, and bounded hygiene review",
    usage: "Usage: forge memory <add|recall|search|insights|review|doctor> [args]",
    load: () => require("./memory"),
  },
  {
    file: "merge.js",
    name: "merge",
    description: "Opt-in conditional auto-merge: merge a PR only when all user-configured rules pass (OFF by default)",
    usage: "Usage: forge merge --auto <pr> --expect-head <40-char-sha> --issue <issue-id>",
    load: () => require("./merge"),
  },
  {
    file: "migrate.js",
    name: "migrate",
    description: "Migrate a Beads issue store into the Forge Kernel with --from beads, or preview the v2→v3 migration (preview only — --dry-run required; applying it is not yet available)",
    usage: "forge migrate --from beads [--dry-run] [--source <dir>] [--json]",
    flags: {"--from <source>":"Migration source. Use \"beads\" to import a Beads issue store into the Kernel.","--source <dir>":"Directory of exported beads *.jsonl files (defaults to auto-detecting .beads/). A split .beads layout is tolerated: files missing from the given dir are also read from a backup/ subdir and the parent dir, so events (under .beads/backup/) and interactions (at .beads/interactions.jsonl) are both picked up regardless of which you point at.","--dry-run":"Read + map only; print what WOULD be imported without writing to the Kernel. Without --from, this is the only supported mode (preview only).","--json":"Emit a structured JSON result (counts + gaps + dryRun flag).","--fixture-corpus":"v2→v3 preview only: also dry-run the source-tree v2 fixture corpus when available."},
    load: () => require("./migrate"),
  },
  {
    file: "new.js",
    name: "new",
    description: "Create Forge extension scaffolds",
    usage: "forge new adapter <name> --kind=review --template=greptile",
    load: () => require("./new"),
  },
  {
    file: "options.js",
    name: "options",
    description: "Inspect runtime graph primitives and config",
    usage: "Usage: forge options <stages|gates|adapters|roles|diff|why <id>|lint> [--json]\n\nInspect resolved runtime graph primitives and project config effects.",
    flags: {"--json":"Emit machine-readable JSON output"},
    load: () => require("./options"),
  },
  {
    file: "orient.js",
    name: "orient",
    description: "Emit bounded project orientation from deterministic source files",
    usage: "Usage: forge orient [--budget N] [--json]",
    load: () => require("./orient"),
  },
  {
    file: "orphans.js",
    name: "orphans",
    description: "Show issues with dangling dependency edges via Forge",
    usage: "forge issue orphans",
    flags: {},
    load: () => require("./orphans"),
  },
  {
    file: "patch.js",
    name: "patch",
    description: "Record and inspect patch intent anchored in patch.md",
    usage: "forge patch record --from-diff\nforge patch status",
    load: () => require("./patch"),
  },
  {
    file: "plan.js",
    name: "plan",
    description: "Create implementation plan from researched feature context",
    load: () => require("./plan"),
  },
  {
    file: "pr.js",
    name: "pr",
    description: "Unified pull-request surface: forge pr ship|preflight|shepherd|merge (wraps ship/preflight/shepherd/merge)",
    usage: "Usage: forge pr <ship|preflight|shepherd|merge> [args]",
    load: () => require("./pr"),
  },
  {
    file: "preflight.js",
    name: "preflight",
    description: "Fast deterministic-gate parity with CI (lint, drift/registry, sonar, affected tests)",
    usage: "forge preflight [--all]",
    flags: {"--all":"Lint/scan the whole tree instead of only changed files"},
    load: () => require("./preflight"),
  },
  {
    file: "prime.js",
    name: "prime",
    description: "Deprecated alias for `forge status -v`: session-entry bounded orientation",
    usage: "Usage: forge prime [--budget N] [--json]  (deprecated — use `forge status -v`)",
    load: () => require("./prime"),
  },
  {
    file: "push.js",
    name: "push",
    description: "Push with quality gates (branch protection + lint + tests)",
    usage: "forge push [--quick] [-- <git-push-args>]",
    flags: {"--quick":"Skip tests (lint-only) for review-cycle pushes"},
    load: () => require("./push"),
  },
  {
    file: "ready.js",
    name: "ready",
    description: "Show ready issues via Forge",
    usage: "forge ready [flags]",
    flags: {},
    load: () => require("./ready"),
  },
  {
    file: "recall.js",
    name: "recall",
    description: "Retrieve project-memory notes from the kernel-backed memory store",
    usage: "Usage: forge recall [query] [--kind <type>] [--limit N] [--all] [--json]",
    flags: {"--kind":"Filter to notes of a type (decision|bugfix|gotcha|...); --type is reserved","--limit":"Cap the number of notes returned","--all":"Include machine/insights records in the no-query listing (query already searches all)","--json":"Emit machine-readable JSON output"},
    load: () => require("./recall"),
  },
  {
    file: "recap.js",
    name: "recap",
    description: "Summarize a single issue from deterministic orientation source files",
    usage: "Usage: forge recap <issue> [--budget N] [--json]",
    load: () => require("./recap"),
  },
  {
    file: "recommend.js",
    name: "recommend",
    description: "Show tool recommendations for the current project",
    load: () => require("./recommend"),
  },
  {
    file: "release.js",
    name: "release",
    description: "Release a claimed issue, or run Forge release readiness gates (forge release check)",
    usage: "Usage: forge release <id>  |  forge release check --target 0.1.0 [--json]  |  forge release regen-audit  |  forge release generate-npm-workflow --expect-head <full-sha>  |  forge release generate-test-workflow --expect-head <full-sha>  |  forge release update-bun-pins --expect-head <full-sha>",
    flags: {"--target <version>":"Release target to check","--expect-head <full-sha>":"Required exact HEAD for protected workflow generation","--json":"Emit the readiness report as JSON"},
    load: () => require("./release"),
  },
  {
    file: "remember.js",
    name: "remember",
    description: "Persist a project-memory note to the kernel-backed memory store",
    usage: "Usage: forge remember <note> [--kind <type>] [--session-summary] [--tag <label>]... [--what <text>] [--why <text>] [--where <text>] [--learned <text>] [--json]",
    flags: {"--kind":"Type the note (decision|bugfix|gotcha|...) — filterable by recall (--type is reserved)","--session-summary":"Alias for --kind session-summary — capture a session summary on exit","--tag":"Attach a search label (repeatable)","--what":"Structured field: what happened/changed","--why":"Structured field: why","--where":"Structured field: where (file/area)","--learned":"Structured field: what was learned","--json":"Emit machine-readable JSON output"},
    load: () => require("./remember"),
  },
  {
    file: "role.js",
    name: "role",
    description: "Bind a role to a skill/ideology in .forge/config.yaml",
    usage: "Usage: forge role <role> --use <skill> [--ideology <name>]",
    load: () => require("./role"),
  },
  {
    file: "serve.js",
    name: "serve",
    description: "Serve the interactive dashboard over 127.0.0.1 (trigger forge verbs from the browser)",
    usage: "forge serve [--port N] [--open]",
    load: () => require("./serve"),
  },
  {
    file: "setup.js",
    name: "setup",
    description: "Initialize forge in a project",
    load: () => require("./setup"),
  },
  {
    file: "shepherd.js",
    name: "shepherd",
    description: "Run one bounded monitor pass over a PR (rerun flaky checks, escalate, hand off — never merges)",
    usage: "Usage: forge shepherd <pr> [--auto-rebase] [--bundle --json] [--pull --json] | forge shepherd events <pr> --since <seq> [--json] | forge shepherd watch <pr> | forge shepherd watch --adopt",
    load: () => require("./shepherd"),
  },
  {
    file: "ship.js",
    name: "ship",
    description: "Create a pull request from validated feature work",
    load: () => require("./ship"),
  },
  {
    file: "show.js",
    name: "show",
    description: "Show an issue via Forge",
    usage: "forge show <id> [flags]",
    flags: {},
    load: () => require("./show"),
  },
  {
    file: "skill.js",
    name: "skill",
    description: "Route, evaluate, score, and coverage-check Forge skills (forge skill for | eval | scores | coverage)",
    usage: "Usage: forge skill for \"<situation>\" [--json]\n       forge skill eval [name] --static [--json]\n       forge skill eval <name> --full --tier 30|100|300 [--json]\n       forge skill scores [--json]\n       forge skill coverage [--json]",
    flags: {"--json":"Emit the machine-readable result","--static":"Score only the deterministic static tier","--full":"Run the controlled behavioral evaluation tier","--tier":"Behavioral corpus tier: 30|100|300"},
    load: () => require("./skill"),
  },
  {
    file: "stage.js",
    name: "stage",
    description: "Record or read an issue's real workflow stage (stage_runs)",
    usage: "Usage: forge stage <issue-id> <stage> --start|--complete   (reads: --current | --list)",
    flags: {"--start":"Open a stage run (status=active)","--complete":"Complete a stage run (status=done)","--substage":"Optional substage label to record","--current":"Print the current stage (latest active, else latest completed)","--list":"Print the full stage-run history for the issue","--json":"Emit machine-readable JSON"},
    load: () => require("./stage"),
  },
  {
    file: "stale.js",
    name: "stale",
    description: "Show stale issues via Forge",
    usage: "forge issue stale [--days <n>]",
    flags: {},
    load: () => require("./stale"),
  },
  {
    file: "status.js",
    name: "status",
    description: "One-glance orientation: where you are, what to run next, and your work",
    usage: "forge status [-v|--verbose] [--full] [--json]",
    flags: {"-v, --verbose":"Print the full session-entry briefing (replaces the deprecated `forge prime`)","--full":"Also show blocked, stale, and recently completed issues","--json":"Emit the machine-readable status envelope"},
    load: () => require("./status"),
  },
  {
    file: "sync.js",
    name: "sync",
    description: "Sync Kernel issue state with the configured sync backend (local-noop until a server/remote is configured)",
    usage: "forge sync",
    flags: {},
    load: () => require("./sync"),
  },
  {
    file: "team.js",
    name: "team",
    description: "Team coordination workflows and sync utilities",
    load: () => require("./team"),
  },
  {
    file: "test.js",
    name: "test",
    description: "Run tests with smart defaults (timeout, affected-only)",
    usage: "forge test [--affected]",
    flags: {"--affected":"Run only tests for changed files"},
    load: () => require("./test"),
  },
  {
    file: "update.js",
    name: "update",
    description: "Update an issue via Forge",
    usage: "forge update <id...> [flags]",
    flags: {},
    load: () => require("./update"),
  },
  {
    file: "upgrade.js",
    name: "upgrade",
    description: "Preview and self-heal safe Forge upgrade readiness",
    usage: "Usage: forge upgrade [--dry-run] [--self-heal]",
    flags: {"--dry-run":"Preview upgrade readiness without writing files","--self-heal":"Apply safe metadata repairs only; does not snapshot or restore"},
    load: () => require("./upgrade"),
  },
  {
    file: "validate.js",
    name: "validate",
    description: "Run validation checks across type, lint, security, and tests",
    usage: "forge validate [--shards N]",
    flags: {"--shards N":"Set the full-suite resource budget"},
    load: () => require("./validate"),
  },
  {
    file: "worktree.js",
    name: "worktree",
    description: "Manage isolated worktrees",
    usage: "forge worktree <create|remove|list> <slug>",
    flags: {"--branch":"Custom branch name (default: feat/<slug>)","--base":"Base ref a new branch forks from (default: the repo default branch, e.g. origin/main)","--issue":"Kernel issue id to link this worktree to (records issue → worktree)","--work-folder":"Repo-relative work-folder this issue owns (records worktree → work-folder + drops a .forge-issue marker)"},
    load: () => require("./worktree"),
  },
];

module.exports = {
  // Absolute path of the canonical commands directory this manifest describes.
  // The registry applies the manifest only when asked to load this exact dir.
  dir: __dirname,
  commands,
};
