/**
 * Static Command Manifest — GENERATED FILE, DO NOT EDIT.
 *
 * Regenerate with: node scripts/gen-command-manifest.js
 * Drift is enforced by test/structural/command-manifest-drift.test.js.
 *
 * Each entry carries the static metadata discovery and help need, snapshotted
 * from the command module's exports, plus a `load` closure with a static
 * relative `require` so `bun build --compile` can still bundle the command
 * graph. The registry (lib/commands/_registry.js) calls `load` only when a
 * command is dispatched, and falls back to `fs.readdirSync` auto-discovery for
 * dev/extension commands.
 *
 * @module commands/_manifest
 */

'use strict';

/**
 * @typedef {Object} ManifestEntry
 * @property {string} file - Command filename (e.g. `status.js`)
 * @property {string} name - Command name used for routing
 * @property {string} description - Human-readable description
 * @property {string} [usage] - Usage string
 * @property {Object<string, string>} [flags] - Flag descriptions
 * @property {boolean} [hidden] - Omitted from the global help listing
 * @property {function(): import("./_registry").CommandModule} load - Requires the command module
 */

/** @type {ManifestEntry[]} */
const commands = [
  {
    file: "adapter.js",
    name: "adapter",
    description: "Manage and test review adapters",
    usage: "forge adapter \u003ctest|list|enable|disable\u003e ...",
    load: () => require(".\u002fadapter"),
  },
  {
    file: "add.js",
    name: "add",
    description: "Record an extension source in forge.lock",
    usage: "Usage: forge add \u003csource\u003e [--name \u003cid\u003e] [--allow-untrusted]",
    flags: {"--name":"Lockfile extension id to record","--allow-untrusted":"Explicitly record an untrusted remote\u002fpackage source"},
    load: () => require(".\u002fadd"),
  },
  {
    file: "audit.js",
    name: "audit",
    description: "Verify Forge lockfile and audit state",
    usage: "Usage: forge audit verify",
    load: () => require(".\u002faudit"),
  },
  {
    file: "blocked.js",
    name: "blocked",
    description: "Show blocked issues via Forge",
    usage: "forge issue blocked [flags]",
    flags: {},
    load: () => require(".\u002fblocked"),
  },
  {
    file: "claim.js",
    name: "claim",
    description: "Claim an issue via Forge",
    usage: "forge claim \u003cid\u003e [flags]",
    flags: {},
    load: () => require(".\u002fclaim"),
  },
  {
    file: "claims.js",
    name: "claims",
    description: "Show active issue leases (claims) via Forge",
    usage: "forge issue claims [--json]",
    flags: {},
    load: () => require(".\u002fclaims"),
  },
  {
    file: "clean.js",
    name: "clean",
    description: "Remove worktrees for merged branches (squash-aware) and fast-forward the default branch",
    usage: "forge clean [--dry-run] [--no-master-sync]",
    flags: {"--dry-run":"Show what would be cleaned without removing","--no-master-sync":"Do not fast-forward the main checkout default branch after cleaning"},
    load: () => require(".\u002fclean"),
  },
  {
    file: "close.js",
    name: "close",
    description: "Close an issue via Forge",
    usage: "forge close \u003cid...\u003e [flags]",
    flags: {},
    load: () => require(".\u002fclose"),
  },
  {
    file: "comment.js",
    name: "comment",
    description: "Add an issue comment via Forge",
    usage: "forge comment \u003cid\u003e \u003cbody...\u003e",
    flags: {},
    load: () => require(".\u002fcomment"),
  },
  {
    file: "control.js",
    name: "control",
    description: "Set tri-state control (mandatory\u002foptional\u002fpermission) for a gate or rail",
    usage: "Usage: forge control \u003cgate-id|rail-id\u003e \u003cmandatory|optional|permission\u003e\n       forge control status [--json]\n\nTri-state control for the gate\u002frail registry. These flags are DECLARED intent\n— today no runtime consumer denies on them (see the guarantee matrix). MCP\u002f\nrules\u002fskills are presence-only and refused — see docs\u002freference\u002fcontrol-plane-guarantees.md.",
    load: () => require(".\u002fcontrol"),
  },
  {
    file: "create.js",
    name: "create",
    description: "Create an issue via Forge",
    usage: "forge create [title] [flags]",
    flags: {},
    load: () => require(".\u002fcreate"),
  },
  {
    file: "dev.js",
    name: "dev",
    description: "Run the TDD development stage with phase guidance",
    load: () => require(".\u002fdev"),
  },
  {
    file: "doc-gate.js",
    name: "doc-gate",
    description: "Detect a repository's structure, or enforce the doc-update gate on a PR",
    usage: "forge doc-gate detect [--json]\n       forge doc-gate check --base \u003cref\u003e --head \u003cref\u003e [--skip] [--json]\n       forge doc-gate init [--force] [--json]\n       forge doc-gate okf \u003cstatus|enable|disable\u003e [--json]\n       forge doc-gate okf generate [--source \u003cdir\u003e] [--out \u003cdir\u003e] [--json]\n       forge doc-gate okf link [--out \u003cdir\u003e] [--json]",
    flags: {"--json":"Emit a structured JSON object instead of the human summary.","--base":"check: base ref\u002fSHA of the pull request.","--head":"check: head ref\u002fSHA of the pull request.","--skip":"check: force a pass (e.g. a no-docs-needed label).","--force":"init: overwrite an existing .docgate.json.","--source":"okf generate: source docs dir (default: auto — docs\u002f or tracked markdown).","--out":"okf generate\u002flink: bundle output dir (default: .okf)."},
    load: () => require(".\u002fdoc-gate"),
  },
  {
    file: "doctor.js",
    name: "doctor",
    description: "Report the filesystem class of the kernel database path (cloud\u002fnetwork\u002flocal)",
    usage: "Usage: forge doctor [--json]",
    load: () => require(".\u002fdoctor"),
  },
  {
    file: "explain.js",
    name: "explain",
    description: "Explain a runtime graph primitive",
    usage: "forge explain \u003cid\u003e [--json]",
    flags: {"--json":"Emit machine-readable JSON output"},
    load: () => require(".\u002fexplain"),
  },
  {
    file: "export.js",
    name: "export",
    description: "Export the Kernel backlog to deterministic git-tracked JSONL (D16 portability projection)",
    usage: "forge export [--dir \u003cpath\u003e] [--dry-run] [--json] [--import]",
    flags: {},
    load: () => require(".\u002fexport"),
  },
  {
    file: "gate.js",
    name: "gate",
    description: "Toggle a workflow gate, or record\u002fquery human-gate approval events",
    usage: "Usage: forge gate \u003cenable|disable|approve|reject|status|check\u003e [\u003cissue-id\u003e] \u003cgate-id\u003e [--ttl \u003cduration\u003e] [--reason \u003ctext\u003e] [--json]\n       forge gate doc \u003cdetect|check|init|okf|...\u003e [args]   (doc-update gate; = forge doc-gate, run `forge doc-gate --help`)",
    load: () => require(".\u002fgate"),
  },
  {
    file: "github.js",
    name: "github",
    description: "Optional clone-local GitHub account selection, automatic routing, and isolated launch",
    usage: "forge github use \u003clogin\u003e [--auto] | auto [--disable] | router --uninstall --force | status [--json] | unset | run -- \u003cprogram\u003e [args...]",
    load: () => require(".\u002fgithub"),
  },
  {
    file: "hooks.js",
    name: "hooks",
    description: "Opt-in install of Forge native hooks into GLOBAL harness config (Codex\u002fHermes)",
    usage: "Usage: forge hooks install --global [--harness codex|hermes|all] [--dry-run]\n       forge hooks session-start --harness \u003cclaude\u003e (machine-facing; emits SessionStart context)\n       forge hooks inbox-pickup --harness \u003cclaude\u003e (machine-facing; emits UserPromptSubmit context)\n       forge hooks shepherd-events --harness \u003cclaude\u003e (machine-facing; emits UserPromptSubmit PR-monitor deltas)\n       forge hooks memory-recall --harness \u003cclaude\u003e (machine-facing; emits UserPromptSubmit query-relevant memory)\n       forge hooks read-attention --harness \u003cclaude\u003e (machine-facing; emits path-matched PreToolUse:Read context)\n       forge hooks capture --harness \u003cclaude\u003e --trigger \u003cprecompact|stop\u003e (machine-facing; captures a session summary on exit)",
    flags: {"--global":"Required consent flag — this command writes home-directory config","--harness":"codex | hermes | all (default: all)","--dry-run":"Preview the merge without writing anything"},
    load: () => require(".\u002fhooks"),
  },
  {
    file: "inbox.js",
    name: "inbox",
    description: "List and ack targeted dashboard instruction comments (compliant comment-back)",
    usage: "Usage: forge inbox [--json]\n       forge inbox ack \u003ccomment_id\u003e",
    flags: {"--json":"Machine-readable envelope for the dashboard \u002f scripts"},
    load: () => require(".\u002finbox"),
  },
  {
    file: "init.js",
    name: "init",
    description: "Initialize Forge adoption config in a fresh repository",
    usage: "Usage: forge init [--profile minimal|standard|full] [--classification critical|standard|refactor] [--harness claude,cursor,codex] [--yes] [--force] [--dry-run]\n\nInitialize the day-one .forge skeleton for a fresh repository.",
    flags: {"--profile \u003cname\u003e":"Adoption profile: minimal, standard, or full","--minimal":"Shortcut for --profile minimal --yes","--standard":"Shortcut for --profile standard --yes","--full":"Shortcut for --profile full --yes","--classification \u003cname\u003e":"Default workflow classification: critical, standard, or refactor","--harness \u003ctargets\u003e":"Comma-separated harness targets: claude, cursor, codex","--yes":"Use the standard profile when no profile is provided","--force":"Overwrite existing day-one .forge files","--dry-run":"Print the generated config YAML without writing files"},
    load: () => require(".\u002finit"),
  },
  {
    file: "insights.js",
    name: "insights",
    description: "Detect recurring evidence patterns and suggest conservative workflow follow-ups",
    usage: "Usage: forge insights [--limit N] [--min-count N] [--since YYYY-MM-DD] [--json]\n       forge insights accept \u003ccandidate-id\u003e [--note text]\n       forge insights reject \u003ccandidate-id\u003e [--note text]",
    load: () => require(".\u002finsights"),
  },
  {
    file: "issue.js",
    name: "issue",
    description: "Manage issues through the Forge command surface",
    usage: "forge issue \u003ccreate|update|claim|release|close|show|list|ready|search|stats|dep\u003e [...]",
    flags: {},
    load: () => require(".\u002fissue"),
  },
  {
    file: "issues.js",
    name: "issues",
    description: "Manage issues through the Forge authority layer",
    usage: "forge issues \u003csubcommand\u003e [...]",
    flags: {},
    hidden: true,
    load: () => require(".\u002fissues"),
  },
  {
    file: "lint.js",
    name: "lint",
    description: "Show issues missing required content via Forge",
    usage: "forge issue lint",
    flags: {},
    load: () => require(".\u002flint"),
  },
  {
    file: "list.js",
    name: "list",
    description: "List issues via Forge",
    usage: "forge list [flags]",
    flags: {},
    load: () => require(".\u002flist"),
  },
  {
    file: "memory.js",
    name: "memory",
    description: "Unified memory surface: add, recall, search, insights, and bounded hygiene review",
    usage: "Usage: forge memory \u003cadd|recall|search|insights|review|doctor\u003e [args]",
    load: () => require(".\u002fmemory"),
  },
  {
    file: "merge.js",
    name: "merge",
    description: "Opt-in conditional auto-merge: merge a PR only when all user-configured rules pass (OFF by default)",
    usage: "Usage: forge merge --auto \u003cpr\u003e --expect-head \u003c40-char-sha\u003e --issue \u003cissue-id\u003e",
    load: () => require(".\u002fmerge"),
  },
  {
    file: "migrate.js",
    name: "migrate",
    description: "Migrate a Beads issue store into the Forge Kernel with --from beads, or preview the v2→v3 migration (preview only — --dry-run required; applying it is not yet available)",
    usage: "forge migrate --from beads [--dry-run] [--source \u003cdir\u003e] [--json]",
    flags: {"--from \u003csource\u003e":"Migration source. Use \"beads\" to import a Beads issue store into the Kernel.","--source \u003cdir\u003e":"Directory of exported beads *.jsonl files (defaults to auto-detecting .beads\u002f). A split .beads layout is tolerated: files missing from the given dir are also read from a backup\u002f subdir and the parent dir, so events (under .beads\u002fbackup\u002f) and interactions (at .beads\u002finteractions.jsonl) are both picked up regardless of which you point at.","--dry-run":"Read + map only; print what WOULD be imported without writing to the Kernel. Without --from, this is the only supported mode (preview only).","--json":"Emit a structured JSON result (counts + gaps + dryRun flag).","--fixture-corpus":"v2→v3 preview only: also dry-run the source-tree v2 fixture corpus when available."},
    load: () => require(".\u002fmigrate"),
  },
  {
    file: "new.js",
    name: "new",
    description: "Create Forge extension scaffolds",
    usage: "forge new adapter \u003cname\u003e --kind=review --template=greptile",
    load: () => require(".\u002fnew"),
  },
  {
    file: "options.js",
    name: "options",
    description: "Inspect runtime graph primitives and config",
    usage: "Usage: forge options \u003cstages|gates|adapters|roles|diff|why \u003cid\u003e|lint\u003e [--json]\n\nInspect resolved runtime graph primitives and project config effects.",
    flags: {"--json":"Emit machine-readable JSON output"},
    load: () => require(".\u002foptions"),
  },
  {
    file: "orient.js",
    name: "orient",
    description: "Emit bounded project orientation from deterministic source files",
    usage: "Usage: forge orient [--budget N] [--json]",
    load: () => require(".\u002forient"),
  },
  {
    file: "orphans.js",
    name: "orphans",
    description: "Show issues with dangling dependency edges via Forge",
    usage: "forge issue orphans",
    flags: {},
    load: () => require(".\u002forphans"),
  },
  {
    file: "patch.js",
    name: "patch",
    description: "Record and inspect patch intent anchored in patch.md",
    usage: "forge patch record --from-diff\nforge patch status",
    load: () => require(".\u002fpatch"),
  },
  {
    file: "plan.js",
    name: "plan",
    description: "Create implementation plan from researched feature context",
    load: () => require(".\u002fplan"),
  },
  {
    file: "pr.js",
    name: "pr",
    description: "Unified pull-request surface: forge pr link|ship|preflight|shepherd|merge",
    usage: "Usage: forge pr \u003clink|ship|preflight|shepherd|merge\u003e [args]",
    load: () => require(".\u002fpr"),
  },
  {
    file: "preflight.js",
    name: "preflight",
    description: "Fast deterministic-gate parity with CI (lint, drift\u002fregistry, sonar, affected tests)",
    usage: "forge preflight [--all]",
    flags: {"--all":"Lint\u002fscan the whole tree instead of only changed files"},
    load: () => require(".\u002fpreflight"),
  },
  {
    file: "prime.js",
    name: "prime",
    description: "Deprecated alias for `forge status -v`: session-entry bounded orientation",
    usage: "Usage: forge prime [--budget N] [--json]  (deprecated — use `forge status -v`)",
    load: () => require(".\u002fprime"),
  },
  {
    file: "push.js",
    name: "push",
    description: "Push with quality gates (branch protection + lint + tests)",
    usage: "forge push [--quick] [-- \u003cgit-push-args\u003e]",
    flags: {"--quick":"Skip tests (lint-only) for review-cycle pushes"},
    load: () => require(".\u002fpush"),
  },
  {
    file: "ready.js",
    name: "ready",
    description: "Show ready issues via Forge",
    usage: "forge ready [flags]",
    flags: {},
    load: () => require(".\u002fready"),
  },
  {
    file: "recall.js",
    name: "recall",
    description: "Retrieve project-memory notes from the kernel-backed memory store",
    usage: "Usage: forge recall [query] [--kind \u003ctype\u003e] [--limit N] [--all] [--json]",
    flags: {"--kind":"Filter to notes of a type (decision|bugfix|gotcha|...); --type is reserved","--limit":"Cap the number of notes returned","--all":"Include machine\u002finsights records in the no-query listing (query already searches all)","--json":"Emit machine-readable JSON output"},
    load: () => require(".\u002frecall"),
  },
  {
    file: "recap.js",
    name: "recap",
    description: "Summarize a single issue from deterministic orientation source files",
    usage: "Usage: forge recap \u003cissue\u003e [--budget N] [--json]",
    load: () => require(".\u002frecap"),
  },
  {
    file: "recommend.js",
    name: "recommend",
    description: "Show tool recommendations for the current project",
    load: () => require(".\u002frecommend"),
  },
  {
    file: "release.js",
    name: "release",
    description: "Release a claimed issue, or run Forge release readiness gates (forge release check)",
    usage: "Usage: forge release \u003cid\u003e  |  forge release check --target 0.1.0 [--json]  |  forge release regen-audit  |  forge release generate-npm-workflow --expect-head \u003cfull-sha\u003e  |  forge release generate-test-workflow --expect-head \u003cfull-sha\u003e  |  forge release generate-size-workflow --expect-head \u003cfull-sha\u003e  |  forge release update-bun-pins [--to \u003cX.Y.Z\u003e] --expect-head \u003cfull-sha\u003e",
    flags: {"--target \u003cversion\u003e":"Release target to check","--expect-head \u003cfull-sha\u003e":"Required exact HEAD for protected workflow generation","--json":"Emit the readiness report as JSON"},
    load: () => require(".\u002frelease"),
  },
  {
    file: "remember.js",
    name: "remember",
    description: "Persist a project-memory note to the kernel-backed memory store",
    usage: "Usage: forge remember \u003cnote\u003e [--kind \u003ctype\u003e] [--session-summary] [--tag \u003clabel\u003e]... [--what \u003ctext\u003e] [--why \u003ctext\u003e] [--where \u003ctext\u003e] [--learned \u003ctext\u003e] [--json]",
    flags: {"--kind":"Type the note (decision|bugfix|gotcha|...) — filterable by recall (--type is reserved)","--session-summary":"Alias for --kind session-summary — capture a session summary on exit","--tag":"Attach a search label (repeatable)","--what":"Structured field: what happened\u002fchanged","--why":"Structured field: why","--where":"Structured field: where (file\u002farea)","--learned":"Structured field: what was learned","--json":"Emit machine-readable JSON output"},
    load: () => require(".\u002fremember"),
  },
  {
    file: "role.js",
    name: "role",
    description: "Bind a role to a skill\u002fideology in .forge\u002fconfig.yaml",
    usage: "Usage: forge role \u003crole\u003e --use \u003cskill\u003e [--ideology \u003cname\u003e]",
    load: () => require(".\u002frole"),
  },
  {
    file: "serve.js",
    name: "serve",
    description: "Serve the interactive dashboard over 127.0.0.1 (trigger forge verbs from the browser)",
    usage: "forge serve [--port N] [--open]",
    load: () => require(".\u002fserve"),
  },
  {
    file: "setup.js",
    name: "setup",
    description: "Initialize forge in a project",
    load: () => require(".\u002fsetup"),
  },
  {
    file: "shepherd.js",
    name: "shepherd",
    description: "Run one bounded monitor pass over a PR (rerun flaky checks, escalate, hand off — never merges)",
    usage: "Usage: forge shepherd \u003cpr\u003e [--auto-rebase] [--bundle --json] [--pull --json] | forge shepherd events \u003cpr\u003e --since \u003cseq\u003e [--json] | forge shepherd watch \u003cpr\u003e | forge shepherd watch --adopt",
    load: () => require(".\u002fshepherd"),
  },
  {
    file: "ship.js",
    name: "ship",
    description: "Create a pull request from validated feature work",
    load: () => require(".\u002fship"),
  },
  {
    file: "show.js",
    name: "show",
    description: "Show an issue via Forge",
    usage: "forge show \u003cid\u003e [flags]",
    flags: {},
    load: () => require(".\u002fshow"),
  },
  {
    file: "skill.js",
    name: "skill",
    description: "Route, evaluate, score, and coverage-check Forge skills (forge skill for | eval | scores | coverage)",
    usage: "Usage: forge skill for \"\u003csituation\u003e\" [--json]\n       forge skill eval [name] --static [--json]\n       forge skill eval \u003cname\u003e --full --tier 30|100|300 [--json]\n       forge skill scores [--json]\n       forge skill coverage [--json]",
    flags: {"--json":"Emit the machine-readable result","--static":"Score only the deterministic static tier","--full":"Run the controlled behavioral evaluation tier","--tier":"Behavioral corpus tier: 30|100|300"},
    load: () => require(".\u002fskill"),
  },
  {
    file: "stage.js",
    name: "stage",
    description: "Record or read an issue's real workflow stage (stage_runs)",
    usage: "Usage: forge stage \u003cissue-id\u003e \u003cstage\u003e --start|--complete   (reads: --current | --list)",
    flags: {"--start":"Open a stage run (status=active)","--complete":"Complete a stage run (status=done)","--substage":"Optional substage label to record","--current":"Print the current stage (latest active, else latest completed)","--list":"Print the full stage-run history for the issue","--json":"Emit machine-readable JSON"},
    load: () => require(".\u002fstage"),
  },
  {
    file: "stale.js",
    name: "stale",
    description: "Show stale issues via Forge",
    usage: "forge issue stale [--days \u003cn\u003e]",
    flags: {},
    load: () => require(".\u002fstale"),
  },
  {
    file: "status.js",
    name: "status",
    description: "One-glance orientation: where you are, what to run next, and your work",
    usage: "forge status [-v|--verbose] [--full] [--json]",
    flags: {"-v, --verbose":"Print the full session-entry briefing (replaces the deprecated `forge prime`)","--full":"Also show blocked, stale, and recently completed issues","--json":"Emit the machine-readable status envelope"},
    load: () => require(".\u002fstatus"),
  },
  {
    file: "sync.js",
    name: "sync",
    description: "Sync Kernel issue state with the configured sync backend (local-noop until a server\u002fremote is configured)",
    usage: "forge sync",
    flags: {},
    load: () => require(".\u002fsync"),
  },
  {
    file: "team.js",
    name: "team",
    description: "Team coordination workflows and sync utilities",
    load: () => require(".\u002fteam"),
  },
  {
    file: "test.js",
    name: "test",
    description: "Run tests with smart defaults (timeout, affected-only)",
    usage: "forge test [--affected]",
    flags: {"--affected":"Run only tests for changed files"},
    load: () => require(".\u002ftest"),
  },
  {
    file: "update.js",
    name: "update",
    description: "Update an issue via Forge",
    usage: "forge update \u003cid...\u003e [flags]",
    flags: {},
    load: () => require(".\u002fupdate"),
  },
  {
    file: "upgrade.js",
    name: "upgrade",
    description: "Preview and self-heal safe Forge upgrade readiness",
    usage: "Usage: forge upgrade [--dry-run] [--self-heal]",
    flags: {"--dry-run":"Preview upgrade readiness without writing files","--self-heal":"Apply safe metadata repairs only; does not snapshot or restore"},
    load: () => require(".\u002fupgrade"),
  },
  {
    file: "validate.js",
    name: "validate",
    description: "Run validation checks across type, lint, security, and tests",
    usage: "forge validate [--shards N]",
    flags: {"--shards N":"Set the full-suite resource budget"},
    load: () => require(".\u002fvalidate"),
  },
  {
    file: "worktree.js",
    name: "worktree",
    description: "Manage isolated worktrees",
    usage: "forge worktree \u003ccreate|remove|list\u003e \u003cslug\u003e",
    flags: {"--branch":"Custom branch name (default: feat\u002f\u003cslug\u003e)","--base":"Base ref a new branch forks from (default: the repo default branch, e.g. origin\u002fmain)","--issue":"Kernel issue id to link this worktree to (records issue → worktree)","--work-folder":"Repo-relative work-folder this issue owns (records worktree → work-folder + drops a .forge-issue marker)"},
    load: () => require(".\u002fworktree"),
  },
];

module.exports = {
  // Absolute path of the canonical commands directory this manifest describes.
  // The registry applies the manifest only when asked to load this exact dir.
  dir: __dirname,
  commands,
};
