/**
 * Command Registry — Auto-Discovery
 *
 * Scans a commands directory for .js files, validates each exports
 * { name, description, handler }, and builds a routing Map.
 *
 * Follows the same fs.readdirSync() pattern as lib/plugin-manager.js.
 *
 * @module _registry
 */

const { existsSync, readdirSync } = require('node:fs');
const path = require('node:path');
const { normalizeStageId } = require('../workflow/stages');

// Static command manifest (bundleable fast path). This is a static require so
// `bun build --compile` can bundle the command graph; the file is generated by
// scripts/gen-command-manifest.js and drift-checked in test/structural. In a dev
// checkout before generation (or if removed) it may be absent — fall back to
// readdir auto-discovery below.
let STATIC_MANIFEST = null;
try {
  STATIC_MANIFEST = require('./_manifest');
} catch (err) {
  if (err.code !== 'MODULE_NOT_FOUND') {
    console.warn(`[registry] Failed to load static manifest: ${err.message}`);
  }
  STATIC_MANIFEST = null;
}

/**
 * @typedef {Object} CommandModule
 * @property {string} name - Command name used for routing
 * @property {string} description - Human-readable description
 * @property {function(Array, Object, string, Object=): Promise<*>} handler - Async command handler (4th arg: resolved command opts)
 * @property {string} [usage] - Usage string (optional)
 * @property {Object<string, string>} [flags] - Flag descriptions (optional)
 */

/**
 * Validate that a module exports the required command interface.
 *
 * @param {*} mod - The required module
 * @returns {{ valid: boolean, reason?: string }}
 */
function validateCommand(mod) {
  if (!mod || typeof mod !== 'object') {
    return { valid: false, reason: 'module does not export an object' };
  }
  if (typeof mod.name !== 'string' || !mod.name) {
    return { valid: false, reason: 'missing or invalid "name" export' };
  }
  if (typeof mod.description !== 'string' || !mod.description) {
    return { valid: false, reason: 'missing or invalid "description" export' };
  }
  if (typeof mod.handler !== 'function') {
    return { valid: false, reason: 'missing or invalid "handler" export' };
  }
  return { valid: true };
}

/**
 * Load and discover command modules from a directory.
 *
 * Scans `commandsDir` for `.js` files (excluding files starting with `_`),
 * validates each module exports `{ name, description, handler }`, and builds
 * a routing Map keyed by command name.
 *
 * Malformed modules are skipped with a `console.warn` — other commands
 * continue loading. Duplicate command names warn and skip the later file.
 *
 * @param {string} commandsDir - Absolute path to the commands directory
 * @returns {{ commands: Map<string, CommandModule>, getHelp: () => string }}
 */
function addCommand(commands, file, mod) {
  const validation = validateCommand(mod);
  if (!validation.valid) {
    console.warn(`[registry] Skipping ${file}: ${validation.reason}`);
    return;
  }

  if (commands.has(mod.name)) {
    console.warn(
      `[registry] Skipping ${file}: duplicate command name "${mod.name}"`
    );
    return;
  }

  commands.set(mod.name, mod);
}

function loadCommands(commandsDir) {
  /** @type {Map<string, CommandModule>} */
  const commands = new Map();

  // Files already contributed by the static manifest — skip re-requiring them
  // during the readdir pass so they neither double-load nor warn as duplicates.
  const seenFiles = new Set();

  // 1) Static manifest fast path (bundleable). Applied only when the caller asks
  //    for the exact canonical commands dir the manifest describes; extension
  //    dirs fall through to readdir below. In a compiled binary there is no real
  //    commands dir on disk, so the manifest is the only path that resolves.
  if (
    STATIC_MANIFEST &&
    Array.isArray(STATIC_MANIFEST.commands) &&
    commandsDir &&
    path.resolve(commandsDir) === path.resolve(STATIC_MANIFEST.dir)
  ) {
    for (const entry of STATIC_MANIFEST.commands) {
      seenFiles.add(entry.file);
      addCommand(commands, entry.file, entry.module);
    }
  }

  // 2) readdir auto-discovery (dev/extension fallback). Picks up command files
  //    not covered by the manifest — including brand-new files a developer or
  //    user drops in without regenerating the manifest — preserving extensibility.
  if (commandsDir && existsSync(commandsDir)) {
    const files = readdirSync(commandsDir)
      .filter(f => f.endsWith('.js') && !f.startsWith('_'))
      .sort(); // deterministic order — first file wins on duplicates

    for (const file of files) {
      if (seenFiles.has(file)) continue;

      let mod;
      try {
        mod = require(path.join(commandsDir, file));
      } catch (_err) {
        console.warn(`[registry] Skipping ${file}: failed to load — ${_err.message}`);
        continue;
      }

      addCommand(commands, file, mod);
    }
  }

  return {
    commands,
    getHelp: () => buildHelp(commands),
  };
}

/**
 * Build a formatted help string from discovered commands.
 *
 * @param {Map<string, CommandModule>} commands
 * @returns {string}
 */
function buildHelp(commands) {
  if (commands.size === 0) {
    return 'No commands available.';
  }

  const lines = ['Available commands:', ''];

  // Find the longest name for alignment
  let maxLen = 0;
  for (const name of commands.keys()) {
    if (name.length > maxLen) maxLen = name.length;
  }

  for (const [name, cmd] of commands) {
    const padding = ' '.repeat(maxLen - name.length + 2);
    lines.push(`  ${name}${padding}${cmd.description}`);
  }

  return lines.join('\n');
}

function isStageCommand(commandName) {
  return normalizeStageId(commandName) !== null;
}

async function executeCommand(commands, commandName, args, flags, projectRoot, options = {}) {
  const command = commands.get(commandName);
  if (!command) {
    return { success: false, error: `Unknown command: ${commandName}` };
  }

  try {
    if (typeof options.enforceStage === 'function' && isStageCommand(commandName)) {
      const enforcement = await options.enforceStage({
        commandName,
        args,
        flags,
        projectRoot,
        command,
      });

      if (enforcement?.allowed === false) {
        return {
          success: false,
          error: enforcement.error ?? `Stage ${commandName} is blocked.`,
          enforcement,
        };
      }
    }

    // Forward a resolved per-command opts object as the handler's 4th arg. Issue/
    // alias handlers read it (shouldUseKernelBroker(opts)); other handlers ignore
    // it. Backward-compatible: defaults to {} so existing 3-arg handlers are
    // unaffected.
    return await command.handler(args, flags, projectRoot, options.commandOpts ?? {});
  } catch (err) {
    return {
      success: false,
      error: err?.message ?? `Failed to execute ${commandName}`,
    };
  }
}

module.exports = { loadCommands, validateCommand, executeCommand };
